### ISSUE TITLE
out of memory for train lora of  wan t2v 14B on 24G Vram

### ISSUE THREAD

**Issue by twoldogs** [tdrussell/diffusion-pipe#164]
I encountered an error :CUDA error: out of memory for train lora of  wan t2v 14B on a 4090 24G
I set the block swap to 22.
it seems to fail to enable block swapping.

# Block swapping is supported for Wan, HunyuanVideo, Flux, and Chroma. This value controls the number
# of blocks kept offloaded to RAM. Increasing it lowers VRAM use, but has a performance penalty. The
# exactly performance penalty depends on the model and the type of training you are doing (e.g. images vs video).
# Block swapping only works for LoRA training, and requires pipeline_stages=1.
blocks_to_swap = 22

[model]
type = 'wan'
# Can load HunyuanVideo entirely from the ckpt path set up for the official inference scripts.
ckpt_path = '../models/Wan2.1-T2V-14B'
# Or you can load it by pointing to all the ComfyUI files.
#transformer_path = '/data2/imagegen_models/hunyuan_video_comfyui/hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors'
##llm_path = '/data2/imagegen_models/hunyuan_video_comfyui/llava-llama-3-8b-text-encoder-tokenizer'
#clip_path = '/data2/imagegen_models/hunyuan_video_comfyui/clip-vit-large-patch14'
# Base dtype used for all models.
dtype = 'bfloat16'
# Hunyuan Video supports fp8 for the transformer when training LoRA.
transformer_dtype = 'float8'
# How to sample timesteps to train on. Can be logit_normal or uniform.
timestep_sample_method = 'logit_normal'
----------------------------------------------------------------------------------------------------
 The following  traceback were produced:
I set the block swap to 20 

WARNING:datasets.arrow_dataset:num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
caching metadata
Map: 100%|██████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 15457.20 examples/s]Map: 100%|█████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 5704.32 examples/s]Map: 100%|███████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 2066.67 examples/s]Map: 100%|███████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 2144.88 examples/s]Map: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 451.49 examples/s]caching latents: ../input
caching latents: (0.7937005259840997, 1)
caching latents: (448, 576, 1)
caching latents: (1.0, 1)
caching latents: (512, 512, 1)
caching latents: (0.5, 1)
caching latents: (352, 736, 1)
num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
WARNING:datasets.arrow_dataset:num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
caching latents: (0.6299605249474366, 1)
caching latents: (416, 640, 1)
num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
WARNING:datasets.arrow_dataset:num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
caching latents: (1.2599210498948732, 1)
caching latents: (576, 448, 1)
num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
WARNING:datasets.arrow_dataset:num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
caching text embeddings: ../input
caching text embeddings: (0.7937005259840997, 1)
caching text embeddings: (1.0, 1)
caching text embeddings: (0.5, 1)
num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
WARNING:datasets.arrow_dataset:num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
caching text embeddings: (0.6299605249474366, 1)
num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
WARNING:datasets.arrow_dataset:num_proc must be <= 4. Reducing num_proc to 4 for dataset of size 4.
caching text embeddings: (1.2599210498948732, 1)
num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
WARNING:datasets.arrow_dataset:num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
trainable params: 153,354,240 || all params: 14,441,845,824 || trainable%: 1.0619
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/hunyuanlora/diffusion-pipe/train.py", line 408, in <module>
[rank0]:     model.enable_block_swap(blocks_to_swap)
[rank0]:   File "/root/hunyuanlora/diffusion-pipe/models/wan.py", line 587, in enable_block_swap
[rank0]:     self.offloader.prepare_block_devices_before_forward(blocks)
[rank0]:   File "/root/hunyuanlora/diffusion-pipe/utils/offloading.py", line 259, in prepare_block_devices_before_forward
[rank0]:     weights_to_device(b, torch.device('cpu'))  # make sure weights are on cpu
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/hunyuanlora/diffusion-pipe/utils/offloading.py", line 119, in weights_to_device
[rank0]:     module.weight.data = module.weight.data.to(device, non_blocking=True)
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W318 01:29:36.347221705 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2025-03-18 01:29:38,992] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 632
[2025-03-18 01:29:39,031] [ERROR] [launch.py:325:sigkill_handler] ['/root/miniconda3/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/wan.toml'] exits with return code = 1

**Comment by twoldogs** [comment]
> Windows or linux? How big is your dataset and what resolution/frames you set in config? I'm not sure if this command is available on windows but when you type nvidia-smi how much gpu memory is already taken before you launch training?

I use it on wsl, and i check the vram during the training. it is about 1g taken before start,and only reach about 8 G vram for the loading process, then it crash.

**Comment by twoldogs** [comment]
> Windows or linux? How big is your dataset and what resolution/frames you set in config? I'm not sure if this command is available on windows but when you type nvidia-smi how much gpu memory is already taken before you launch training?

it was the default setting and I only use picture;

# If you just want to use predetermined (width, height, frames) size buckets, see the example cosmos_dataset.toml
# file for how you can do that.
resolutions = [512]

**Comment by arczewski** [comment]
How much ram do you have?
I'm training on 3090 24gb with blocks_to_swap set to 15 and it is working for me but I have plenty of RAM(128GB) so maybe that is also a factor.

**Comment by twoldogs** [comment]
infact,when I turn off block swap, I can properly train the lora.

**Comment by tdrussell** [comment]
>it is about 1g taken before start,and only reach about 8 G vram for the loading process, then it crash.

This seems odd, if indeed it is OOMing without using all the memory. Use nvtop and watch the memory usage closely. Typically if you OOM, the graph will show it spike all the way up. Also the error message is strange. When I OOM I always see it say more details about how much memory was already used, and how much it tried to allocate which triggered the OOM.

I searched google briefly, and saw some reports of others encountering this error even when memory is not fully used. It looks like some driver or CUDA issue could cause this.

First thing to do is confirm whether the block swapping really is somehow spiking your VRAM usage all the way and OOMing you.

**Comment by twoldogs** [comment]
> > it is about 1g taken before start,and only reach about 8 G vram for the loading process, then it crash.
> 
> This seems odd, if indeed it is OOMing without using all the memory. Use nvtop and watch the memory usage closely. Typically if you OOM, the graph will show it spike all the way up. Also the error message is strange. When I OOM I always see it say more details about how much memory was already used, and how much it tried to allocate which triggered the OOM.
> 
> I searched google briefly, and saw some reports of others encountering this error even when memory is not fully used. It looks like some driver or CUDA issue could cause this.
> 
> First thing to do is confirm whether the block swapping really is somehow spiking your VRAM usage all the way and OOMing you.

now I think it does is related to the  memory,I give wsl 55 G ram and 40 G swap, eventhough the wls show there was more than 30 G buff/cache which should be release when needed, but there is no more "free memory" . And there was a IO spike about 45wa,means swap has been used. THANK ANYWAY. Turn out, I don't really need block swapping if I only use image.

**Comment by BenDes21** [comment]
> > it is about 1g taken before start,and only reach about 8 G vram for the loading process, then it crash.
> 
> This seems odd, if indeed it is OOMing without using all the memory. Use nvtop and watch the memory usage closely. Typically if you OOM, the graph will show it spike all the way up. Also the error message is strange. When I OOM I always see it say more details about how much memory was already used, and how much it tried to allocate which triggered the OOM.
> 
> I searched google briefly, and saw some reports of others encountering this error even when memory is not fully used. It looks like some driver or CUDA issue could cause this.
> 
> First thing to do is confirm whether the block swapping really is somehow spiking your VRAM usage all the way and OOMing you.

Hi, possible to know where set the block swapping and the unsloth activation checkpointing

**Comment by wwwku11** [comment]
I also encountered this problem. cuda 12.4,  video memory is 20G and the memory is 96G. I will report an error when I use block swap. It's very puzzling, I wonder if you have found a solution.

**Comment by tdrussell** [comment]
>No solution but to drastically reduce the train resolution

If you are using all of the VRAM saving settings together, you should be able to train on 512x512x81 sized videos. [This config file](https://github.com/tdrussell/diffusion-pipe/blob/main/examples/wan_14b_min_vram.toml) has all the settings enabled. On my system it trains at that size with just over 22GB VRAM usage. These are just the settings listed under the Reducing VRAM section of the readme.

The full 832x480x81, or whatever it is, is likely too much for 24GB. But this should allow 512x512x81 (and aspect ratios of 512 in general). If it doesn't, something is wrong and I will try to find out what it is.

**Comment by tdrussell** [comment]
I will go ahead and close this. The above linked config file demonstrates all the VRAM saving settings, and seems to be about as optimized as you can get.
