### ISSUE TITLE
problems converting from flash attn 2

### ISSUE THREAD

**Issue by Mistermango23** [tdrussell/diffusion-pipe#178]
something went error:

⚡ main ~/diffusion-pipe NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config examples/hunyuan_video.toml
[2025-03-27 17:35:34,533] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 17:35:37,473] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-03-27 17:35:37,473] [INFO] [runner.py:607:main] cmd = /home/zeus/miniconda3/envs/cloudspace/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config examples/hunyuan_video.toml
[2025-03-27 17:35:39,091] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 17:35:41,895] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2025-03-27 17:35:41,895] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2025-03-27 17:35:41,895] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2025-03-27 17:35:41,895] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2025-03-27 17:35:41,895] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2025-03-27 17:35:41,896] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2025-03-27 17:35:41,896] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.17.1-1
[2025-03-27 17:35:41,896] [INFO] [launch.py:139:main] 0 NCCL_P2P_DISABLE=1
[2025-03-27 17:35:41,896] [INFO] [launch.py:139:main] 0 NCCL_IB_DISABLE=1
[2025-03-27 17:35:41,896] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-03-27 17:35:41,896] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-03-27 17:35:41,896] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-03-27 17:35:41,896] [INFO] [launch.py:164:main] dist_world_size=1
[2025-03-27 17:35:41,896] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-03-27 17:35:41,897] [INFO] [launch.py:256:main] process 29680 spawned with command: ['/home/zeus/miniconda3/envs/cloudspace/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml']
[2025-03-27 17:35:43,601] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1976, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/models/bloom/modeling_bloom.py", line 38, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/modeling_utils.py", line 54, in <module>
    from .integrations.flash_attention import flash_attention_forward
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/integrations/flash_attention.py", line 5, in <module>
    from ..modeling_flash_attention_utils import _flash_attention_forward
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 29, in <module>
    from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 15, in <module>
    import flash_attn_2_cuda as flash_attn_gpu
ImportError: /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/teamspace/studios/this_studio/diffusion-pipe/train.py", line 28, in <module>
    from utils.patches import apply_patches
  File "/teamspace/studios/this_studio/diffusion-pipe/utils/patches.py", line 8, in <module>
    import peft
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/__init__.py", line 17, in <module>
    from .auto import (
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/auto.py", line 31, in <module>
    from .config import PeftConfig
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/utils/__init__.py", line 17, in <module>
    from .other import (
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/utils/other.py", line 34, in <module>
    from .constants import (
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/utils/constants.py", line 16, in <module>
    from transformers import BloomPreTrainedModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1965, in __getattr__
    value = getattr(module, name)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1964, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1978, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bloom.modeling_bloom because of the following error (look up to see its traceback):
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
[2025-03-27 17:35:48,923] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 29680
[2025-03-27 17:35:48,923] [ERROR] [launch.py:325:sigkill_handler] ['/home/zeus/miniconda3/envs/cloudspace/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1

but I use on [lightning.ai](https://lightning.ai/)

**Comment by frostyfrolics** [comment]
> you probably have a bad flash_attention installation, I'm having issues on that myself, I managed to fix the undefined symbol by reinstalling pytorch for cuda128 and then compiling flash_attention myself, but now I'm running on a different issue:
> 
> ```
> [rank0]:   File "/mnt/c/Users/helto/diffusion-pipe/flash-attention/flash_attn/flash_attn_interface.py", line 170, in _flash_attn_varlen_forward
> [rank0]:     out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(
> [rank0]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:
> [rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
> [rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```

I have this same issue. I am using a 5090 so I am using the nightly versions for torch. 
I pulled and built flash-attention locally to get a .whl and installed that into my diffusion-pip venv, but I still get the same error as the one you posted when trying to train Wan2.1. 
I'm not sure what to do or how to make flash-attention happy, the latest version is suppose to support Rockwell/sm_120 but I don't know what I could be doing wrong here.

**Comment by HDANILO** [comment]
> > you probably have a bad flash_attention installation, I'm having issues on that myself, I managed to fix the undefined symbol by reinstalling pytorch for cuda128 and then compiling flash_attention myself, but now I'm running on a different issue:
> > ```
> > [rank0]:   File "/mnt/c/Users/helto/diffusion-pipe/flash-attention/flash_attn/flash_attn_interface.py", line 170, in _flash_attn_varlen_forward
> > [rank0]:     out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(
> > [rank0]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> > [rank0]:
> > [rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
> > [rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> > ```
> 
> I have this same issue. I am using a 5090 so I am using the nightly versions for torch. I pulled and built flash-attention locally to get a .whl and installed that into my diffusion-pipe venv, but I still get the same error as the one you posted when trying to train Wan2.1. I'm not sure what to do or how to make flash-attention happy, the latest version is suppose to support Rockwell/sm_120 but I don't know what I could be doing wrong here.

I managed to fix the problem yesterday, here's the whole thread if you're willing to read it all: https://github.com/Dao-AILab/flash-attention/issues/1563

But A.K.A. after many different attempts to fix the issue, I had to purge my WSL distro, install a new distro, and then setup the environment from 0 making sure NVCC was pointing to 12.8 and nvidia-smi also reported 12.8, then I installed torch torchvision and torchaudio for cuda128, and then checkout flash-attention repo and installed with `python setup.py install`.

This also fixed other issues that I was having installing, for instance, pytorch3d. Turns out, I had an outdated toolkit installed on the WSL from before my 5090, and that probably left some libraries corrupting my installations.

**Comment by frostyfrolics** [comment]
> I managed to fix the problem yesterday, here's the whole thread if you're willing to read it all: [Dao-AILab/flash-attention#1563](https://github.com/Dao-AILab/flash-attention/issues/1563)
> 
> But A.K.A. after many different attempts to fix the issue, I had to purge my WSL distro, install a new distro, and then setup the environment from 0 making sure NVCC was pointing to 12.8 and nvidia-smi also reported 12.8, then I installed torch torchvision and torchaudio for cuda128, and then checkout flash-attention repo and installed with `python setup.py install`.
> 
> This also fixed other issues that I was having installing, for instance, pytorch3d. Turns out, I had an outdated toolkit installed on the WSL from before my 5090, and that probably left some libraries corrupting my installations.

Yep, I was just reading that as you replied. That was it... I had to cleanup up my WSL env and re-install cuda tools fresh, then rebuilt flash-attn and it finally works. Thanks!

**Comment by tdrussell** [comment]
I will go ahead and close this assuming the original issue is resolved.

**Comment by AnhTuWally** [comment]
This issue occurs to me on Debian. I found out that this issue was due to torch 2.7.0. Downgrade it to torch 2.6.0 and reinstall flash_attn work for me.
