### ISSUE TITLE
Multi-GPU 5090s - Trying again

### ISSUE THREAD

**Issue by Oruli** [tdrussell/diffusion-pipe#235]
Hi, here is the trace I'm getting, torch 2.8 latest nightly, pipeline stages = 2

```
[2025-04-23 17:06:15,561] [INFO] [config.py:1007:print]   zero_force_ds_cpu_optimizer .. True
[2025-04-23 17:06:15,561] [INFO] [config.py:1007:print]   zero_optimization_stage ...... 0
[2025-04-23 17:06:15,561] [INFO] [config.py:993:print_user_config]   json = {
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_accumulation_steps": 1, 
    "gradient_clipping": 1.0, 
    "steps_per_print": 1
}
[2025-04-23 17:06:15,561] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=1 micro_batch_size=1
[2025-04-23 17:06:15,561] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2025-04-23 17:06:15,739] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2025-04-23 17:06:15,766] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=16 [0, 16) STAGE_PARAMS=105168896 (105.169M) TOTAL_PARAMS=294780928 (294.781M) UNIQUE_PARAMS=294780928 (294.781M)
[2025-04-23 17:06:15,766] [INFO] [engine.py:165:__init__] RANK=1 STAGE=1 LAYERS=36 [16, 52) STAGE_PARAMS=189612032 (189.612M) TOTAL_PARAMS=294780928 (294.781M) UNIQUE_PARAMS=294780928 (294.781M)
[rank1]:[E423 17:06:16.181433982 ProcessGroupNCCL.cpp:1981] [PG ID 2 PG GUID 2 Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x88 (0x73ee355806a8 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x55 (0x73ee3551c223 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3e2 (0x73eeadcad402 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x73edc51165c6 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x70 (0x73edc51268b0 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x76c (0x73edc5127f7c in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x73edc51299cd in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdbbf4 (0x73eeb14dbbf4 in /home/r/miniconda3/envs/diffusion-pipe/bin/../lib/libstdc++.so.6)
frame #8: <unknown function> + 0xa1e2e (0x73eeb22a1e2e in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x133a4c (0x73eeb2333a4c in /lib/x86_64-linux-gnu/libc.so.6)

[rank0]:[E423 17:06:16.233438241 ProcessGroupNCCL.cpp:1981] [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x88 (0x74778a1806a8 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x55 (0x74778a11c223 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3e2 (0x7478026ad402 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x747719d165c6 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x70 (0x747719d268b0 in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x76c (0x747719d27f7c in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x747719d299cd in /home/r/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdbbf4 (0x747805edbbf4 in /home/r/miniconda3/envs/diffusion-pipe/bin/../lib/libstdc++.so.6)
frame #8: <unknown function> + 0xa1e2e (0x747806ea1e2e in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x133a4c (0x747806f33a4c in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by tdrussell** [comment]
1. Try passing CUDA_LAUNCH_BLOCKING=1 like it suggests, and see if that makes it show exactly what line of code is failing
2. Try with pipeline_stages=1 and nf4 (assuming this is HiDream). See if it works with 1 GPU.

**Comment by tdrussell** [comment]
Okay, so Deepspeed is failing inside the initialize call with some CUDA error. You will have to debug on your own, because this is likely specific to your setup and I can't reproduce this failure.

Things to investigate: is it happening with all models? Is it a problem with the specific CUDA or PyTorch version you have installed? Does other pytorch code (e.g. other trainers) work? Does it work if you only enable a single GPU?

**Comment by tdrussell** [comment]
You should check that basic multi-GPU functionality works at all on your setup. What happens if you run this script, does it complete?
```
import os
import torch
import torch.distributed as dist

rank = os.environ['RANK']
print(rank)
dist.init_process_group(backend='nccl')
tensor = torch.rand((10,), device=f'cuda:{rank}')
dist.barrier()

if rank == 0:
    dist.send(tensor, dst=1)
elif rank == 1:
    dist.recv(tensor, src=0)
dist.barrier()
print(tensor)

dist.all_reduce(tensor)
dist.barrier()
print(tensor)
```
run using a command like: ```CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc-per-node=2 ~/tmp/test_multigpu.py```

**Comment by tdrussell** [comment]
So plain PyTorch GPU communication ops work. But deepspeed.initialize() is always failing when it does its version of cross-GPU communication. Myself and other users have this working, but it fails specifically with multiple 5090s, and you are probably the only person who has tried that setup.

I would raise an issue with Deepspeed. I don't think I've done anything wrong in the application code, and it is likely an internal Deepspeed problem. Without being able to reproduce the error myself, there's not much more I can do.

**Comment by AutoAwesome** [comment]
I have the same issue with an 5090 + 4090. I can run training on both cards individually. But when using both together I get also `an illegal memory access was encountered`.

**Comment by pinballelectronica** [comment]
FWIW I have 2x4090's 2.71 12.9 wsl2 py312 and I get Deepspeed complaints when using two GPU's.  One GPU, no problem, two, OOM..  I am trying to train BF16 so that may not be possible at the most conversative settings.  That said, with one (dedicated) GPU it makes it all the way through latent caching and bucketing whereas with 2 GPU's it isntantly OOM's.  

With two GPU's-  With one it complains about something pickle which is probably a dataset problem  on my side..fwiw.  To me this suggests something DS but what do I know, I play pinball.

[rank1]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:3356, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
[rank1]: ncclUnhandledCudaError: Call to CUDA function failed.
[rank1]: Last error:
[rank1]: Cuda failure 2 'out of memory'
feh:9447:9711 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct
feh:9447:9711 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct

**Comment by Oruli** [comment]
@tdrussell  I've not got anywhere with deepspeed devs, really nothing else we can do?

No other tuner supports multi-gpu but this one that I can find, so it's super frustrating to have an idle 5090 that I spent out for

**Comment by tdrussell** [comment]
I commented on the deepspeed issue with the code for a test script that works for me.

You want to find a minimal test script that reproduces the issue, so we can confirm that it is a problem specifically with 2x5090, and confirm if it is unrelated to the specific application code of diffusion-pipe (which I suspect to be true, given the nature of the error).

**Comment by noman-git** [comment]
@tdrussell 
> I commented on the deepspeed issue with the code for a test script that works for me.

I used that very script that you commented there and **it worked**.

But when I did try to run the training using this config:
```
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1
```

Command used:
`CUDA_VISIBLE_DEVICES=0,1 deepspeed train.py   --deepspeed   --config examples/wan.toml`

I still get the **same error as** @Oruli

**Comment by tdrussell** [comment]
@noman-git I realized that the script provided in the other issue won't exercise the codepath that caused the original error. You need to make it use the pipeline parallel engine. Can you try this one with 2 GPUs?

```
import torch
import argparse
import deepspeed
from deepspeed.pipe import PipelineModule

def parse_args():
    parser = argparse.ArgumentParser()
    parser = deepspeed.add_config_arguments(parser)
    parser.add_argument('--local_rank', type=int, default=-1, help='local rank passed from distributed launcher')
    return parser.parse_args()

def main():
    args = parse_args()
    deepspeed.init_distributed()

    # Dummy model for testing
    model = PipelineModule([torch.nn.Linear(10, 10)], num_stages=1)

    # Initialize DeepSpeed
    model_engine, _, _, _ = deepspeed.initialize(
        args=args,
        model=model,
        model_parameters=model.parameters()
    )

    # Print which GPU the model is on
    print(f"Model is on device: {model_engine.device}")

if __name__ == "__main__":
    main()
```

**Comment by noman-git** [comment]
@tdrussell Yeah this script works fine as well

**Comment by Oruli** [comment]
@tdrussell I get the below with your updated script:

```
[2025-07-28 11:08:30,568] [INFO] [config.py:944:print_user_config]   json = {
    "train_batch_size": 8, 
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_accumulation_steps": 4, 
    "fp16": {
        "enabled": true
    }
}
[2025-07-28 11:08:30,568] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=4 micro_batch_size=1
[2025-07-28 11:08:30,568] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2025-07-28 11:08:30,585] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=1 [0, 1) STAGE_PARAMS=110 (0.000M) TOTAL_PARAMS=110 (0.000M) UNIQUE_PARAMS=110 (0.000M)
Model is on device: cuda:0
Model is on device: cuda:1
[rank0]:[W728 11:08:31.959431767 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[rank1]:[W728 11:08:31.292704504 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-07-28 11:08:33,812] [INFO] [launch.py:351:main] Process 43830 exits successfully.
[2025-07-28 11:08:33,812] [INFO] [launch.py:351:main] Process 43829 exits successfully.
```

**Comment by tdrussell** [comment]
Okay, good to see that basic functionality works. But that's basically all I can do to help with debugging, since I can't reproduce the error on my setup with my GPUs. The only thing to do at this point is to gradually add things to the test script, to make it closer to what diffusion-pipe is doing, and pinpoint what exactly causes the error to happen.

**Comment by XodrocSO** [comment]
Might have found part of the issue, I was trying to get DeepSpeed NCCL working in a different project, using PyTorch 2.7.1 with CUDA 12.8 support.. That's when I noticed the NCCL it shipped with is CUDA 12.2!  Not Blackwell compatible.  

Switched to PyTorch Nightly with CUDA 12.9 and it's NCCL says CUDA 12.9 as well, got further in my project after that.

**Comment by Oruli** [comment]
> Might have found part of the issue, I was trying to get DeepSpeed NCCL working in a different project, using PyTorch 2.7.1 with CUDA 12.8 support.. That's when I noticed the NCCL it shipped with is CUDA 12.2! Not Blackwell compatible.
> 
> Switched to PyTorch Nightly with CUDA 12.9 and it's NCCL says CUDA 12.9 as well, got further in my project after that.

I setup this repo using the default install instructions and haven't updated anything, could that be why?

`conda install nvidia/label/cuda-12.8.1::cuda-nvcc`

I am using pytorch nightly though:

`pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128`

In my environment these are some packages installed and versions, what should I be looking for?

```
cuda-nvcc                               12.9.86          0                nvidia/label/cuda-12.9.1
nvidia-nccl-cu12                        2.26.2           pypi_0           pypi
torch                                   2.7.1+cu128      pypi_0           pypi
```

**Comment by Colnb83** [comment]
I'm having the same issue and error with 2x RTX 6000, must be a cuda/blackwell issue?

**Comment by Oruli** [comment]
> I'm having the same issue and error with 2x RTX 6000, must be a cuda/blackwell issue?

This is the other thread, I've had these 2 x 5090s since launch day and gutted nobody has been able to replicate and fix it

https://github.com/deepspeedai/DeepSpeed/issues/7261

edit: @Colnb83  Are you using the standard setup here, using Conda etc? Mind sharing packages etc as I did above to compare?

**Comment by Colnb83** [comment]
Yes standard setup, copy and paste essentially from the README page

**Comment by tdrussell** [comment]
https://github.com/tdrussell/diffusion-pipe/blob/main/test/debug_deepspeed_init.py

Can anybody with multiple Blackwell GPUs run this test script? This ought to reproduce the problem in the most minimal way while still using all the relevant parts of the diffusion-pipe codebase.

You will need to:
1. Edit the config file in that directory to point to the right model on disk
2. Run using the command at the top of the python file

Try it with both pipeline_stages=1 and pipeline_stages=2 in the config file. I would expect this to reproduce the error you are seeing in deepspeed.initialize() when running full training. I would be very surprised if training gives an error but this test script somehow does not.

**Comment by XodrocSO** [comment]
@tdrussell  
is the Wan submodule missing in the current version?  Last time I did training was Hunyuan, and says missing Wan module.  I have 1x RTX 6000 Pro and 2x 5090 to test with, for the moment.

**Comment by tdrussell** [comment]
Since the Wan2.2 update all the Wan code should be included directly instead of relying on a submodule. I don't understand git submodules very well so I don't know what it says is missing for you; maybe if you still have the local directory for the Wan submodule it will say something.

**Comment by tdrussell** [comment]
If anybody is trying to use WSL, see https://github.com/tdrussell/diffusion-pipe/issues/314#issuecomment-3146253593

WSL might just be weird and need special drivers or CUDA versions. I would recommend using native Linux if you are doing any serious AI work. WSL is great if it works for you, but Linux is always going to be more stable and better supported for AI and ML things.

**Comment by XodrocSO** [comment]
Reinstalled Diffusion Pipe, Had to download the full Wan Model

Initially got the error I expected with PyTorch 2.7.1 CUDA 12.8, since I know it has an outdated NCCL component.

Updated to PyTorch Nightly 12.9, had to rebuild Flash-Attn.

Got pipeline/timeout errors, disabled IpV6 in WSL.

Finally launched using these arguments:

@echo off
cmd /k wsl -d Ubuntu -- bash -c "source /home/blah/miniconda3/etc/profile.d/conda.sh && conda activate diffusion-pipe && cd /home/blah/diffusion-pipe && export NCCL_P2P_DISABLE=1 && export NCCL_IB_DISABLE=1 && export NCCL_SOCKET_IFNAME=lo && export TORCH_DISTRIBUTED_TIMEOUT=7200 && export MASTER_ADDR=127.0.0.1 && export NCCL_DEBUG=INFO && deepspeed --num_gpus=3 --master_port=29502 --module test.debug_deepspeed_init --deepspeed 2> nccl_debug.log"

Ran out of System RAM(128GB) with 3 GPUS, so with 2 GPUS I got this far:

[2025-08-02 12:16:18,158] [INFO] [comm.py:675:init_distributed] cdb=None
[2025-08-02 12:16:18,158] [INFO] [comm.py:675:init_distributed] cdb=None
[2025-08-02 12:16:18,158] [INFO] [comm.py:706:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
SEED_LAYERS=False BASE_SEED=1234 SEED_FN=None
Using topology: {ProcessCoord(pipe=0, data=0): 0, ProcessCoord(pipe=1, data=0): 1}
[2025-08-02 12:17:56,283] [INFO] [module.py:398:_partition_layers] Partitioning pipeline stages with method parameters
stage=0 layers=21
     0: InitialLayer
     1: TransformerLayer
     2: TransformerLayer
     3: TransformerLayer
     4: TransformerLayer
     5: TransformerLayer
     6: TransformerLayer
     7: TransformerLayer
     8: TransformerLayer
     9: TransformerLayer
    10: TransformerLayer
    11: TransformerLayer
    12: TransformerLayer
    13: TransformerLayer
    14: TransformerLayer
    15: TransformerLayer
    16: TransformerLayer
    17: TransformerLayer
    18: TransformerLayer
    19: TransformerLayer
    20: TransformerLayer
stage=1 layers=21
    21: TransformerLayer
    22: TransformerLayer
    23: TransformerLayer
    24: TransformerLayer
    25: TransformerLayer
    26: TransformerLayer
    27: TransformerLayer
    28: TransformerLayer
    29: TransformerLayer
    30: TransformerLayer
    31: TransformerLayer
    32: TransformerLayer
    33: TransformerLayer
    34: TransformerLayer
    35: TransformerLayer
    36: TransformerLayer
    37: TransformerLayer
    38: TransformerLayer
    39: TransformerLayer
    40: TransformerLayer
    41: FinalLayer
  loss: loss_fn
[2025-08-02 12:18:22,436] [INFO] [config.py:744:__init__] Config mesh_device None world_size = 1
[2025-08-02 12:18:22,708] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed info: version=0.17.0, git-hash=unknown, git-branch=unknown
[2025-08-02 12:18:22,708] [INFO] [config.py:744:__init__] Config mesh_device None world_size = 1
[2025-08-02 12:18:34,624] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 11013
[2025-08-02 12:18:34,632] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 11014
[2025-08-02 12:18:34,653] [ERROR] [launch.py:325:sigkill_handler] ['/home/blah/miniconda3/envs/diffusion-pipe/bin/python3.12', '-u', '-m', 'test.debug_deepspeed_init', '--local_rank=1', '--deepspeed'] exits with return code = 1

EDIT:  It seems "partition_activations" is not recognized, removed that and made it further, leading to a dreaded 999 error.. Investigating more, including the CUDA Toolkit issue, and will report back.

**Comment by Colnb83** [comment]
I haven't had any luck with wsl and training, so I just switch into native
Linux to do it, I'd recommend you do the same

**Comment by XodrocSO** [comment]
I now have Dual 5090s training in WSL.   Turned out the source of my 999 error with NCCL is the RTX 6000 Pro.   It doesn't appear to be fully supported yet.  Going OOM was caused by a mistake trying to add Zero optimizations and some other nonsense. I pass the test script fine if I exclude the RTX 6000 Pro.

**Comment by Colnb83** [comment]
doesn't help with dual 6000's but I can still train on them individually

**Comment by Oruli** [comment]
Can we stick to native Linux in the topic as that's where the issue was logged?

@Colnb83 Did you run the latest test script?

@tdrussell I'll run and output as soon as I'm back at my box, thanks for still trying to debug this.

**Comment by Colnb83** [comment]
I couldn't get the script to run, had a module utils not found error, didn't have time to work out what it was missing

**Comment by xrlexpert** [comment]
Hi @Colnb83, @XodrocSO, @Oruli 

I'm encountering the exact same issue on my setup: 4x RTX PRO 6000 (Blackwell, sm_120) with DeepSpeed ZeRO-2. The training crashes during DeepSpeed optimizer initialization with "CUDA error: an illegal memory access was encountered", and the stack trace points to `torch._C._nn.flatten_dense_tensors` inside DeepSpeed's `stage_1_and_2.py`.

I've tried:
- Setting `NCCL_P2P_DISABLE=1`, `NCCL_IB_DISABLE=1`, and correct `NCCL_SOCKET_IFNAME`.
- Switching `attn_implementation` from flash-attn to `sdpa`.
- Modifying DeepSpeed config (`"overlap_comm": false`, `"contiguous_gradients": false`).
- The same script runs fine on a single GPU, but fails with 4 GPUs.

Did you manage to resolve it? If so, could you please share the exact versions you are using (PyTorch, CUDA, DeepSpeed, NCCL) and any workaround that worked for you?

My environment:
- PyTorch 2.7.0+cu128
- CUDA 12.8
- DeepSpeed 0.18.9
- NCCL 2.26.2
- NVIDIA Driver 575+

Thanks in advance!
