### ISSUE TITLE
black output with Chroma LoRA and `loss: nan` while training

### ISSUE THREAD

**Issue by lhovav** [tdrussell/diffusion-pipe#254]
Hi,

I followed the Code's tutorial, setup everything, took the `chroma` model section and pasted it to the `.toml` file, set the dataset, but I get black images when generating with the LoRA `.safetensors` and as mentioned in the title I get `loss: nan` while training - any idea why?
**first time I use diffusion-pipe, so likely my mistake somewhere.

output:
```
venv) root@921b62c2ba45:/workspace/diffusion-pipe# NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config /workspace/diffusion-pipe/examples/chroma_lora.toml
[2025-05-06 07:35:52,335] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-06 07:36:14,404] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-05-06 07:36:14,405] [INFO] [runner.py:605:main] cmd = /workspace/diffusion-pipe/venv/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config /workspace/diffusion-pipe/examples/chroma_lora.toml
[2025-05-06 07:36:22,018] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-06 07:36:44,736] [INFO] [launch.py:139:main] 0 NCCL_IB_DISABLE=1
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NCCL_P2P_DISABLE=1
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.17.1-1
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2025-05-06 07:36:44,737] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2025-05-06 07:36:44,737] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-05-06 07:36:44,737] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-05-06 07:36:44,737] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-05-06 07:36:44,738] [INFO] [launch.py:164:main] dist_world_size=1
[2025-05-06 07:36:44,738] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-05-06 07:36:44,740] [INFO] [launch.py:256:main] process 40546 spawned with command: ['/workspace/diffusion-pipe/venv/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', '/workspace/diffusion-pipe/examples/chroma_lora.toml']
[2025-05-06 07:36:58,920] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-06 07:37:23,646] [INFO] [comm.py:669:init_distributed] cdb=None
[2025-05-06 07:37:23,647] [INFO] [comm.py:700:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 47.28it/s]
Loading pipeline components...:  67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                              | 4/6 [00:00<00:00,  7.72it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  6.71it/s]
using video_clip_mode=single_beginning
using framerate=None
caching metadata
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1114.73 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 519.89 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 828.13 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 534.58 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 578.18 examples/s]
caching latents: /workspace/diffusion-pipe/dataset
caching latents: (0.7937005259840997, 1)
caching latents: (864, 1088, 1)
caching latents: (0.6299605249474366, 1)
caching latents: (768, 1216, 1)
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching latents: (1.0, 1)
caching latents: (960, 960, 1)
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
caching latents: (0.5, 1)
caching latents: (672, 1344, 1)
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching latents: (1.2599210498948732, 1)
caching latents: (1088, 864, 1)
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: /workspace/diffusion-pipe/dataset
caching text embeddings: (0.7937005259840997, 1)
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 2145.70 examples/s]
caching text embeddings: (0.6299605249474366, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 868.81 examples/s]
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: (1.0, 1)
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1260.46 examples/s]
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
caching text embeddings: (0.5, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 879.55 examples/s]
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: (1.2599210498948732, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 850.48 examples/s]
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching metadata
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 788.59 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 341.25 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 462.28 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 303.98 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 348.62 examples/s]
caching latents: /workspace/diffusion-pipe/dataset
caching latents: (0.7937005259840997, 1)
caching latents: (864, 1088, 1)
caching latents: (0.6299605249474366, 1)
caching latents: (768, 1216, 1)
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching latents: (1.0, 1)
caching latents: (960, 960, 1)
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
caching latents: (0.5, 1)
caching latents: (672, 1344, 1)
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching latents: (1.2599210498948732, 1)
caching latents: (1088, 864, 1)
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: /workspace/diffusion-pipe/dataset
caching text embeddings: (0.7937005259840997, 1)
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1873.61 examples/s]
caching text embeddings: (0.6299605249474366, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 747.91 examples/s]
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: (1.0, 1)
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1405.41 examples/s]
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
caching text embeddings: (0.5, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 835.02 examples/s]
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: (1.2599210498948732, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 854.47 examples/s]
num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
trainable params: 112,066,560 || all params: 9,012,049,984 || trainable%: 1.2435
SEED_LAYERS=False BASE_SEED=1234 SEED_FN=None
Using topology: {ProcessCoord(pipe=0, data=0): 0}
[2025-05-06 07:37:41,322] [INFO] [module.py:398:_partition_layers] Partitioning pipeline stages with method parameters
stage=0 layers=60
     0: InitialLayer
     1: TransformerWrapper
     2: TransformerWrapper
     3: TransformerWrapper
     4: TransformerWrapper
     5: TransformerWrapper
     6: TransformerWrapper
     7: TransformerWrapper
     8: TransformerWrapper
     9: TransformerWrapper
    10: TransformerWrapper
    11: TransformerWrapper
    12: TransformerWrapper
    13: TransformerWrapper
    14: TransformerWrapper
    15: TransformerWrapper
    16: TransformerWrapper
    17: TransformerWrapper
    18: TransformerWrapper
    19: TransformerWrapper
    20: concatenate_hidden_states
    21: SingleTransformerWrapper
    22: SingleTransformerWrapper
    23: SingleTransformerWrapper
    24: SingleTransformerWrapper
    25: SingleTransformerWrapper
    26: SingleTransformerWrapper
    27: SingleTransformerWrapper
    28: SingleTransformerWrapper
    29: SingleTransformerWrapper
    30: SingleTransformerWrapper
    31: SingleTransformerWrapper
    32: SingleTransformerWrapper
    33: SingleTransformerWrapper
    34: SingleTransformerWrapper
    35: SingleTransformerWrapper
    36: SingleTransformerWrapper
    37: SingleTransformerWrapper
    38: SingleTransformerWrapper
    39: SingleTransformerWrapper
    40: SingleTransformerWrapper
    41: SingleTransformerWrapper
    42: SingleTransformerWrapper
    43: SingleTransformerWrapper
    44: SingleTransformerWrapper
    45: SingleTransformerWrapper
    46: SingleTransformerWrapper
    47: SingleTransformerWrapper
    48: SingleTransformerWrapper
    49: SingleTransformerWrapper
    50: SingleTransformerWrapper
    51: SingleTransformerWrapper
    52: SingleTransformerWrapper
    53: SingleTransformerWrapper
    54: SingleTransformerWrapper
    55: SingleTransformerWrapper
    56: SingleTransformerWrapper
    57: SingleTransformerWrapper
    58: SingleTransformerWrapper
    59: FinalLayer
  loss: loss_fn
[2025-05-06 07:37:43,130] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed info: version=0.16.7, git-hash=unknown, git-branch=unknown
[2025-05-06 07:37:43,130] [INFO] [config.py:735:__init__] Config mesh_device None world_size = 1
[2025-05-06 07:37:43,226] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2025-05-06 07:37:43,254] [INFO] [logging.py:107:log_dist] [Rank 0] Using client callable to create basic optimizer
[2025-05-06 07:37:43,255] [INFO] [logging.py:107:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2025-05-06 07:37:43,303] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW
[2025-05-06 07:37:43,303] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Final Optimizer = AdamW
[2025-05-06 07:37:43,303] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed using configured LR scheduler = None
[2025-05-06 07:37:43,303] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2025-05-06 07:37:43,303] [INFO] [logging.py:107:log_dist] [Rank 0] step=0, skipped=0, lr=[2e-05], mom=[0.0]
[2025-05-06 07:37:43,309] [INFO] [config.py:1003:print] DeepSpeedEngine configuration:
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   activation_checkpointing_config  {
    "partition_activations": false, 
    "contiguous_memory_optimization": false, 
    "cpu_checkpointing": false, 
    "number_checkpoints": null, 
    "synchronize_checkpoint_boundary": false, 
    "profile": false
}
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'intra_op_parallelism': 1, 'single_submit': False, 'overlap_events': True, 'use_gds': False}
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   amp_enabled .................. False
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   amp_params ................... False
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   autotuning_config ............ {
    "enabled": false, 
    "start_step": null, 
    "end_step": null, 
    "metric_path": null, 
    "arg_mappings": null, 
    "metric": "throughput", 
    "model_info": null, 
    "results_dir": "autotuning_results", 
    "exps_dir": "autotuning_exps", 
    "overwrite": true, 
    "fast": true, 
    "start_profile_step": 3, 
    "end_profile_step": 5, 
    "tuner_type": "gridsearch", 
    "tuner_early_stopping": 5, 
    "tuner_num_trials": 50, 
    "model_info_path": null, 
    "mp_size": 1, 
    "max_train_batch_size": null, 
    "min_train_batch_size": 1, 
    "max_train_micro_batch_size_per_gpu": 1.024000e+03, 
    "min_train_micro_batch_size_per_gpu": 1, 
    "num_tuning_micro_batch_sizes": 3
}
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   bfloat16_enabled ............. False
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   bfloat16_immediate_grad_update  False
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   checkpoint_parallel_write_pipeline  False
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   checkpoint_tag_validation_enabled  True
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   checkpoint_tag_validation_fail  False
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x72d6b182df30>
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   communication_data_type ...... None
[2025-05-06 07:37:43,310] [INFO] [config.py:1007:print]   compile_config ............... deepcompile=False free_activation=False offload_activation=False offload_opt_states=False double_buffer=True symmetric_memory=False debug_log=False offload_parameters=False sync_before_reduce=False sync_after_reduce=False sync_before_allgather=False sync_after_allgather=False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   curriculum_enabled_legacy .... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   curriculum_params_legacy ..... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   data_efficiency_config ....... {'enabled': False, 'seed': 1234, 'data_sampling': {'enabled': False, 'num_epochs': 1000, 'num_workers': 0, 'pin_memory': False, 'curriculum_learning': {'enabled': False}, 'dynamic_batching': {'enabled': False, 'lr_scaling_method': 'linear', 'min_batch_size': 1, 'max_batch_size': None, 'sequence_picking_order': 'dataloader', 'verbose': False}}, 'data_routing': {'enabled': False, 'random_ltd': {'enabled': False, 'layer_token_lr_schedule': {'enabled': False}}}}
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   data_efficiency_enabled ...... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   dataloader_drop_last ......... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   disable_allgather ............ False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   dump_state ................... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   dynamic_loss_scale_args ...... None
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_enabled ........... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_gas_boundary_resolution  1
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_layer_num ......... 0
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_max_iter .......... 100
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_stability ......... 1e-06
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_tol ............... 0.01
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   eigenvalue_verbose ........... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   elasticity_enabled ........... False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   flops_profiler_config ........ {
    "enabled": false, 
    "recompute_fwd_factor": 0.0, 
    "profile_step": 1, 
    "module_depth": -1, 
    "top_modules": 1, 
    "detailed": true, 
    "output_file": null
}
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   fp16_auto_cast ............... None
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   fp16_enabled ................. False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   fp16_master_weights_and_gradients  False
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   global_rank .................. 0
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   grad_accum_dtype ............. None
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   gradient_accumulation_steps .. 1
[2025-05-06 07:37:43,311] [INFO] [config.py:1007:print]   gradient_clipping ............ 1.0
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   gradient_predivide_factor .... 1.0
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   graph_harvesting ............. False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   hybrid_engine ................ enabled=False max_out_tokens=512 inference_tp_size=1 release_inference_cache=False pin_parameters=True tp_gather_partition_size=8
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   initial_dynamic_scale ........ 65536
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   load_universal_checkpoint .... False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   loss_scale ................... 0
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   memory_breakdown ............. False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   mics_hierarchial_params_gather  False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   mics_shard_size .............. -1
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   monitor_config ............... tensorboard=TensorBoardConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') comet=CometConfig(enabled=False, samples_log_interval=100, project=None, workspace=None, api_key=None, experiment_name=None, experiment_key=None, online=None, mode=None) wandb=WandbConfig(enabled=False, group=None, team=None, project='deepspeed') csv_monitor=CSVConfig(enabled=False, output_path='', job_name='DeepSpeedJobName')
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   nebula_config ................ {
    "enabled": false, 
    "persistent_storage_path": null, 
    "persistent_time_interval": 100, 
    "num_of_version_in_retention": 2, 
    "enable_nebula_load": true, 
    "load_path": null
}
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   optimizer_legacy_fusion ...... False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   optimizer_name ............... None
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   optimizer_params ............. None
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0, 'pipe_partitioned': True, 'grad_partitioned': True}
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   pld_enabled .................. False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   pld_params ................... False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   prescale_gradients ........... False
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   scheduler_name ............... None
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   scheduler_params ............. None
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   seq_parallel_communication_data_type  torch.float32
[2025-05-06 07:37:43,312] [INFO] [config.py:1007:print]   sparse_attention ............. None
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   sparse_gradients_enabled ..... False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   steps_per_print .............. 1
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   tensor_parallel_config ....... dtype=torch.float16 autotp_size=0 tp_overlap_comm=False tensor_parallel=TPConfig(tp_size=1, tp_grain_size=1, mpu=None, tp_group=None) injection_policy_tuple=None keep_module_on_host=False replace_with_kernel_inject=False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   timers_config ................ enabled=True synchronized=True
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   train_batch_size ............. 1
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   train_micro_batch_size_per_gpu  1
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   use_data_before_expert_parallel_  False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   use_node_local_storage ....... False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   wall_clock_breakdown ......... False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   weight_quantization_config ... None
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   world_size ................... 1
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   zero_allow_untested_optimizer  False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   zero_config .................. stage=0 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500000000 use_multi_rank_bucket_allreduce=True allgather_partitions=True allgather_bucket_size=500000000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=None offload_optimizer=None sub_group_size=1000000000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50000000 param_persistence_threshold=100000 model_persistence_threshold=9223372036854775807 max_live_parameters=1000000000 max_reuse_distance=1000000000 gather_16bit_weights_on_model_save=False module_granularity_threshold=0 use_all_reduce_for_fetch_params=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False zero_hpz_partition_size=1 zero_quantized_weights=False zero_quantized_nontrainable_weights=False zero_quantized_gradients=False zeropp_loco_param=None mics_shard_size=-1 mics_hierarchical_params_gather=False memory_efficient_linear=True pipeline_loading_checkpoint=False override_module_apply=True log_trace_cache_warnings=False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   zero_enabled ................. False
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   zero_force_ds_cpu_optimizer .. True
[2025-05-06 07:37:43,313] [INFO] [config.py:1007:print]   zero_optimization_stage ...... 0
[2025-05-06 07:37:43,313] [INFO] [config.py:993:print_user_config]   json = {
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_accumulation_steps": 1, 
    "gradient_clipping": 1.0, 
    "steps_per_print": 1
}
[2025-05-06 07:37:43,313] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=1 micro_batch_size=1
[2025-05-06 07:37:43,314] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2025-05-06 07:37:43,354] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=60 [0, 60) STAGE_PARAMS=112066560 (112.067M) TOTAL_PARAMS=112066560 (112.067M) UNIQUE_PARAMS=112066560 (112.067M)
/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:1399: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with device_autocast_ctx, torch.cpu.amp.autocast(**cpu_autocast_kwargs), recompute_context:  # type: ignore[attr-defined]
[2025-05-06 07:37:52,491] [INFO] [logging.py:107:log_dist] [Rank 0] step=1, skipped=0, lr=[3.9800000000000004e-07], mom=[0.0]
steps: 1 loss: nan iter time (s): 8.695 samples/sec: 0.115
[2025-05-06 07:38:00,969] [INFO] [logging.py:107:log_dist] [Rank 0] step=2, skipped=0, lr=[5.960000000000001e-07], mom=[0.0]
steps: 2 loss: nan iter time (s): 8.385 samples/sec: 0.119
```

**Comment by kabachuha** [comment]
Are all your text encoders in the highest precision? I used to get nan when tuning Wan because I had T5 fp8 quantized

**Comment by tdrussell** [comment]
When you set ```diffusers_path = 'black-forest-labs/FLUX.1-schnell'``` is it auto-downloading the Diffusers folder correctly? I have always just manually downloaded and pointed to the path on my disk.

Also for the transformer_path, you are not literally using what you posted, right? That is the example path for me, on my machine. Just checking, I think you must have changed it because it should fail if the path doesn't exist.

**Comment by lhovav** [comment]
Hi, thank you for your code and reply!
> When you set diffusers_path = 'black-forest-labs/FLUX.1-schnell' is it auto-downloading the Diffusers folder correctly? 
I'm not sure, I took it from `ai-toolkit` `train_lora_flux_24gb.yaml` file, the name of the option is `name_or_path: "black-forest-labs/FLUX.1-dev"` under `model` - I trained many LoRAs with that, so I assumed it will work too.

> Also for the transformer_path, you are not literally using what you posted, right? That is the example path for me, on my machine. Just checking, I think you must have changed it because it should fail if the path doesn't exist.

my actual path is something like that: `transformer_path = 'transformer_path = '/root/.cache/huggingface/hub/models--lodestones--Chroma/snapshots/db2174and14be1234c0255a55075c5ce33634fd/chroma-unlocked-v27.safetensors''
`
I'm using `huggingface cli download` command for downloading the model.

I will try to point `diffusers_path` to the model on the disk and will update.

Thank you for the reply!

**Comment by lhovav** [comment]
an update:
the only way I managed to start training was with my initial settings:
```
[model]
type = 'chroma'
diffusers_path = 'black-forest-labs/FLUX.1-schnell'
transformer_path = 'transformer_path = '/root/.cache/huggingface/hub/models--lodestones--Chroma/snapshots/db2174and14be1234c0255a55075c5ce33634fd/chroma-unlocked-v27.safetensors''
dtype = 'bfloat16'
# You can optionally load the transformer in fp8 when training LoRAs.
transformer_dtype = 'float8'
flux_shift = true

# For models that support full fine tuning, simply delete or comment out the [adapter] table to FFT.
[adapter]
type = 'lora'
rank = 32
# Dtype for the LoRA weights you are training.
dtype = 'bfloat16'
# You can initialize the lora weights from a previously trained lora.
#init_from_existing = '/data/diffusion_pipe_training_runs/something/epoch50'

[optimizer]
# AdamW from the optimi library is a good default since it automatically uses Kahan summation when training bfloat16 weights.
# Look at train.py for other options. You could also easily edit the file and add your own.
type = 'adamw_optimi'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
eps = 1e-8
```

It does load the model I can tell you that.

since I am using Runpod - I download the Chroma safetensors file via `huggingface-cli download` and it spits out something like that:
```
/root/.cache/huggingface/hub/models--lodestones--Chroma/snapshots/db2174and14be1234c0255a55075c5ce33634fd/chroma-unlocked-v27.safetensors
```

I also tried to move it to my disk but it failed for some reason (only a small part of the file was moved and the script failed)

can you please share an actual example of a file using Chroma?

Thank you!

**Comment by tdrussell** [comment]
I don't really know what's wrong then. This exact config file works for me (changed only the paths at the top):
```
output_dir = '/data/diffusion_pipe_training_runs/chroma'
dataset = '/home/anon/code/diffusion-pipe-configs/datasets/test.toml'

# training settings
epochs = 1000
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 4
gradient_clipping = 1.0
warmup_steps = 100

# eval settings
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 2
#checkpoint_every_n_epochs = 1
#checkpoint_every_n_minutes = 120
activation_checkpointing = true
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 4
steps_per_print = 1

[model]
type = 'chroma'
diffusers_path = '/data2/imagegen_models/FLUX.1-dev'
transformer_path = '/data2/imagegen_models/chroma/chroma-unlocked-v24.safetensors'
dtype = 'bfloat16'
transformer_dtype = 'float8'
#flux_shift = true

[adapter]
type = 'lora'
rank = 128
dtype = 'bfloat16'

[optimizer]
type = 'adamw_optimi'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
eps = 1e-8
```

It could be something to do with the Runpod environment, or the GPU used. The fact that loss is NaN on the very first step means that it can't even run a forward pass of the model correctly (the weights are updated for the very first time after the loss is computed for the first step).

**Comment by lhovav** [comment]
do you think that this environment is suitable for training?
`runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04`
 together with `pip install torch==2.4.1+cu124 torchvision==0.19.1+cu124 --extra-index-url https://download.pytorch.org/whl/cu124`

Thanks

**Comment by lhovav** [comment]
I'm closing the case, you were right, Python 3.10 wasn't compatible with diffusion-pipe, now with Python 3.12 everything is working beautifully, thank you so much for your help AND code!
