### ISSUE TITLE
3X4090, cuda out of memory,during HiDream training, is this normal?

### ISSUE THREAD

**Issue by samliu315** [tdrussell/diffusion-pipe#255]
I can't use "NF4" because it throws an error when I try to start it. I experimented from 1X to 2X, then 3X4090, and used the nvitop command to monitor VRAM usage. During this process, I saw all three GPUs' VRAM usage spike to 99% simultaneously, and then the training crashed. I haven't had the chance to try 4X4090 yet. Is this normal? What should I do next?

**Comment by samliu315** [comment]
240G memory

**Comment by samliu315** [comment]
I didn't find any mention in main-toml about block swap supporting HiDream, but I still tried enabling it.The training process is running normally now, but I'm not sure if the output Lora will work properly.

**Comment by stierma1** [comment]
I am able to run HiDream across my 2 x 5000 ada's Here is my config hidream.toml 
`# Output path for training runs. Each training run makes a new directory in here.
output_dir = 'data/diffusion_pipe_training_runs/hidream_training'

# Dataset config file.
dataset = 'configs/dataset.toml'
# You can have separate eval datasets. Give them a name for Tensorboard metrics.
# eval_datasets = [
#     {name = 'something', config = 'path/to/eval_dataset.toml'},
# ]

# training settings

# I usually set this to a really high value because I don't know how long I want to train.
epochs = 200
# Batch size of a single forward/backward pass for one GPU.
micro_batch_size_per_gpu = 2
# For mixed video / image training, you can have a different batch size for images.
#image_micro_batch_size_per_gpu = 4
# Pipeline parallelism degree. A single instance of the model is divided across this many GPUs.
pipeline_stages = 2
# Number of micro-batches sent through the pipeline for each training step.
# If pipeline_stages > 1, a higher GAS means better GPU utilization due to smaller pipeline bubbles (where GPUs aren't overlapping computation).
gradient_accumulation_steps = 2
# Grad norm clipping.
gradient_clipping = 1.0
# Learning rate warmup.
warmup_steps = 25

# Block swapping is supported for Wan, HunyuanVideo, Flux, and Chroma. This value controls the number
# of blocks kept offloaded to RAM. Increasing it lowers VRAM use, but has a performance penalty. The
# exactly performance penalty depends on the model and the type of training you are doing (e.g. images vs video).
# Block swapping only works for LoRA training, and requires pipeline_stages=1.
#blocks_to_swap = 20

# eval settings

eval_every_n_epochs = 1
eval_before_first_step = true
# Might want to set these lower for eval so that less images get dropped (eval dataset size is usually much smaller than training set).
# Each size bucket of images/videos is rounded down to the nearest multiple of the global batch size, so higher global batch size means
# more dropped images. Usually doesn't matter for training but the eval set is much smaller so it can matter.
eval_micro_batch_size_per_gpu = 1
# Batch size for images when doing mixed image / video training. Will be micro_batch_size_per_gpu if not set.
#image_eval_micro_batch_size_per_gpu = 4
eval_gradient_accumulation_steps = 1
# If using block swap, you can disable it for eval. Eval uses less memory, so depending on block swapping amount you can maybe get away with
# doing this, and then eval is much faster.
#disable_block_swap_for_eval = true

# misc settings

# Probably want to set this a bit higher if you have a smaller dataset so you don't end up with a million saved models.
save_every_n_epochs = 4
# Can checkpoint the training state every n number of epochs or minutes. Set only one of these. You can resume from checkpoints using the --resume_from_checkpoint flag.
#checkpoint_every_n_epochs = 1
checkpoint_every_n_minutes = 120
# Always set to true unless you have a huge amount of VRAM.
# This can also be 'unsloth' to reduce VRAM even more, with a slight performance hit.
activation_checkpointing = true

# Controls how Deepspeed decides how to divide layers across GPUs. Probably don't change this.
partition_method = 'parameters'
# Alternatively you can use 'manual' in combination with partition_split, which specifies the split points for dividing
# layers between GPUs. For example, with two GPUs, partition_split=[10] puts layers 0-9 on GPU 0, and the rest on GPU 1.
# With three GPUs, partition_split=[10, 20] puts layers 0-9 on GPU 0, layers 10-19 on GPU 1, and the rest on GPU 2.
# Length of partition_split must be pipeline_stages-1.
#partition_split = [N]

# dtype for saving the LoRA or model, if different from training dtype
save_dtype = 'bfloat16'
# Batch size for caching latents and text embeddings. Increasing can lead to higher GPU utilization during caching phase but uses more memory.
caching_batch_size = 1
# How often deepspeed logs to console.
steps_per_print = 1
# How to extract video clips for training from a single input video file.
# The video file is first assigned to one of the configured frame buckets, but then we must extract one or more clips of exactly the right
# number of frames for that bucket.
# single_beginning: one clip starting at the beginning of the video
# single_middle: one clip from the middle of the video (cutting off the start and end equally)
# multiple_overlapping: extract the minimum number of clips to cover the full range of the video. They might overlap some.
# default is single_beginning
video_clip_mode = 'single_beginning'

# This is how you configure HunyuanVideo. Other models will be different. See docs/supported_models.md for
# details on the configuration and options for each model.
[model]
type = 'hidream'
diffusers_path = 'HiDream-ai/HiDream-I1-Full'
llama3_path = 'Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2'
llama3_4bit = false
dtype = 'bfloat16'
transformer_dtype = 'float8'
# Can use nf4 quantization for even more VRAM saving.
#transformer_dtype = 'nf4'
max_llama3_sequence_length = 256
# Can use a resolution-dependent timestep shift, like Flux. Unsure if results are better.
#flux_shift = true
# For models that support full fine tuning, simply delete or comment out the [adapter] table to FFT.
[adapter]
type = 'lora'
rank = 32
# Dtype for the LoRA weights you are training.
dtype = 'bfloat16'
# You can initialize the lora weights from a previously trained lora.
#init_from_existing = '/data/diffusion_pipe_training_runs/something/epoch50'

#[optimizer]
# AdamW from the optimi library is a good default since it automatically uses Kahan summation when training bfloat16 weights.
# Look at train.py for other options. You could also easily edit the file and add your own.
#type = 'adamw_optimi'
#lr = 1e-5
#betas = [0.9, 0.99]
#weight_decay = 0.01
#eps = 1e-8

# Can use this optimizer for a bit less memory usage.
[optimizer]
type = 'AdamW8bitKahan'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
stabilize = false

# Any optimizer not explicitly supported will be dynamically loaded from the pytorch-optimizer library.
# [optimizer]
# type = 'Prodigy'
# lr = 1
# betas = [0.9, 0.99]
# weight_decay = 0.01

[monitoring]
# Set to true and fill in these fields to enable wandb
enable_wandb = false
wandb_api_key = ''
wandb_tracker_name = ''`

**Comment by samliu315** [comment]
> 我可以在我的 2 块 RTX 5000 Ada 上运行 HiDream。这是我的配置文件 hidream.toml。
> 
> ```
> # Output path for training runs. Each training run makes a new directory in here.
> 
> output_dir = 'data/diffusion_pipe_training_runs/hidream_training'
> 
> # Dataset config file.
> dataset = 'configs/dataset.toml'
> # You can have separate eval datasets. Give them a name for Tensorboard metrics.
> # eval_datasets = [
> #     {name = 'something', config = 'path/to/eval_dataset.toml'},
> # ]
> 
> # training settings
> 
> # I usually set this to a really high value because I don't know how long I want to train.
> epochs = 200
> # Batch size of a single forward/backward pass for one GPU.
> micro_batch_size_per_gpu = 2
> # For mixed video / image training, you can have a different batch size for images.
> #image_micro_batch_size_per_gpu = 4
> # Pipeline parallelism degree. A single instance of the model is divided across this many GPUs.
> pipeline_stages = 2
> # Number of micro-batches sent through the pipeline for each training step.
> # If pipeline_stages > 1, a higher GAS means better GPU utilization due to smaller pipeline bubbles (where GPUs aren't overlapping computation).
> gradient_accumulation_steps = 2
> # Grad norm clipping.
> gradient_clipping = 1.0
> # Learning rate warmup.
> warmup_steps = 25
> 
> # Block swapping is supported for Wan, HunyuanVideo, Flux, and Chroma. This value controls the number
> # of blocks kept offloaded to RAM. Increasing it lowers VRAM use, but has a performance penalty. The
> # exactly performance penalty depends on the model and the type of training you are doing (e.g. images vs video).
> # Block swapping only works for LoRA training, and requires pipeline_stages=1.
> #blocks_to_swap = 20
> 
> # eval settings
> 
> eval_every_n_epochs = 1
> eval_before_first_step = true
> # Might want to set these lower for eval so that less images get dropped (eval dataset size is usually much smaller than training set).
> # Each size bucket of images/videos is rounded down to the nearest multiple of the global batch size, so higher global batch size means
> # more dropped images. Usually doesn't matter for training but the eval set is much smaller so it can matter.
> eval_micro_batch_size_per_gpu = 1
> # Batch size for images when doing mixed image / video training. Will be micro_batch_size_per_gpu if not set.
> #image_eval_micro_batch_size_per_gpu = 4
> eval_gradient_accumulation_steps = 1
> # If using block swap, you can disable it for eval. Eval uses less memory, so depending on block swapping amount you can maybe get away with
> # doing this, and then eval is much faster.
> #disable_block_swap_for_eval = true
> 
> # misc settings
> 
> # Probably want to set this a bit higher if you have a smaller dataset so you don't end up with a million saved models.
> save_every_n_epochs = 4
> # Can checkpoint the training state every n number of epochs or minutes. Set only one of these. You can resume from checkpoints using the --resume_from_checkpoint flag.
> #checkpoint_every_n_epochs = 1
> checkpoint_every_n_minutes = 120
> # Always set to true unless you have a huge amount of VRAM.
> # This can also be 'unsloth' to reduce VRAM even more, with a slight performance hit.
> activation_checkpointing = true
> 
> # Controls how Deepspeed decides how to divide layers across GPUs. Probably don't change this.
> partition_method = 'parameters'
> # Alternatively you can use 'manual' in combination with partition_split, which specifies the split points for dividing
> # layers between GPUs. For example, with two GPUs, partition_split=[10] puts layers 0-9 on GPU 0, and the rest on GPU 1.
> # With three GPUs, partition_split=[10, 20] puts layers 0-9 on GPU 0, layers 10-19 on GPU 1, and the rest on GPU 2.
> # Length of partition_split must be pipeline_stages-1.
> #partition_split = [N]
> 
> # dtype for saving the LoRA or model, if different from training dtype
> save_dtype = 'bfloat16'
> # Batch size for caching latents and text embeddings. Increasing can lead to higher GPU utilization during caching phase but uses more memory.
> caching_batch_size = 1
> # How often deepspeed logs to console.
> steps_per_print = 1
> # How to extract video clips for training from a single input video file.
> # The video file is first assigned to one of the configured frame buckets, but then we must extract one or more clips of exactly the right
> # number of frames for that bucket.
> # single_beginning: one clip starting at the beginning of the video
> # single_middle: one clip from the middle of the video (cutting off the start and end equally)
> # multiple_overlapping: extract the minimum number of clips to cover the full range of the video. They might overlap some.
> # default is single_beginning
> video_clip_mode = 'single_beginning'
> 
> # This is how you configure HunyuanVideo. Other models will be different. See docs/supported_models.md for
> # details on the configuration and options for each model.
> [model]
> type = 'hidream'
> diffusers_path = 'HiDream-ai/HiDream-I1-Full'
> llama3_path = 'Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2'
> llama3_4bit = false
> dtype = 'bfloat16'
> transformer_dtype = 'float8'
> # Can use nf4 quantization for even more VRAM saving.
> #transformer_dtype = 'nf4'
> max_llama3_sequence_length = 256
> # Can use a resolution-dependent timestep shift, like Flux. Unsure if results are better.
> #flux_shift = true
> # For models that support full fine tuning, simply delete or comment out the [adapter] table to FFT.
> [adapter]
> type = 'lora'
> rank = 32
> # Dtype for the LoRA weights you are training.
> dtype = 'bfloat16'
> # You can initialize the lora weights from a previously trained lora.
> #init_from_existing = '/data/diffusion_pipe_training_runs/something/epoch50'
> 
> #[optimizer]
> # AdamW from the optimi library is a good default since it automatically uses Kahan summation when training bfloat16 weights.
> # Look at train.py for other options. You could also easily edit the file and add your own.
> #type = 'adamw_optimi'
> #lr = 1e-5
> #betas = [0.9, 0.99]
> #weight_decay = 0.01
> #eps = 1e-8
> 
> # Can use this optimizer for a bit less memory usage.
> [optimizer]
> type = 'AdamW8bitKahan'
> lr = 2e-5
> betas = [0.9, 0.99]
> weight_decay = 0.01
> stabilize = false
> 
> # Any optimizer not explicitly supported will be dynamically loaded from the pytorch-optimizer library.
> # [optimizer]
> # type = 'Prodigy'
> # lr = 1
> # betas = [0.9, 0.99]
> # weight_decay = 0.01
> 
> [monitoring]
> # Set to true and fill in these fields to enable wandb
> enable_wandb = false
> wandb_api_key = ''
> wandb_tracker_name = ''
> wandb_run_name = ''
> ```

Thank you, I checked your toml configuration, even if I use the same configuration, I can't train normally without turning on block swap

**Comment by stierma1** [comment]
How are you starting the job? Does it use all the gpus?  This is how I start mine.  ```NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=2 train.py --deepspeed --config configs/hidream.toml```

**Comment by samliu315** [comment]
I tried using 4x RTX 4090, but it still shows 'CUDA out of memory.' I had to enable 'blockswap' just to start training normally. There’s definitely something wrong here.

![Image](https://github.com/user-attachments/assets/a1aaa3a8-eddc-4c1c-9f00-f6d496d3b216)

**Comment by samliu315** [comment]
When blockswap is enabled, this is the GPU usage for training：

![Image](https://github.com/user-attachments/assets/4bd11a4b-6b57-440a-8236-a90812f81d75)

**Comment by samliu315** [comment]
@tdrussell  So, when I was trying to finetune SDXL using my 4x 4090s, I couldn't use blockswap this time. I'm still getting the exact same error as before:

[rank2]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB. GPU 2 has a total capacity of 23.55 GiB of which 10.69 MiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 22.10 GiB is allocated by PyTorch, and 780.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)"

**Comment by samliu315** [comment]
Now I figured it out. It turns out that I just need to make sure that the * in pipeline_stages = * corresponds to the correct number of GPUs.
