### ISSUE TITLE
"Can't pickle" errors when trying to train Wan2.1-T2V-14B LoRa

### ISSUE THREAD

**Issue by yuhlearn** [tdrussell/diffusion-pipe#287]
I keep running into these error messages which I haven't seen earlier. I've used the same setup successfully before, but now it won't work for some reason.

I train on Runpod, typically using RTX A6000 with at least 48GB RAM, but I've tried other systems and configurations with the same issue. Is it memory related?

I pasted a couple of error messages below. The second one is more common.

**wan_14b_t2v.toml**

```
output_dir = '/workspace/diffusion-pipe/data/output'
dataset = '/workspace/diffusion-pipe/myconf/dataset.toml'

# training settings
epochs = 200
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1
warmup_steps = 10

# eval settings
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 10
checkpoint_every_n_minutes = 120
activation_checkpointing = 'unsloth'
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 1
video_clip_mode = 'single_beginning'

[model]
type = 'wan'
ckpt_path = '/workspace/diffusion-pipe/Wan2.1-T2V-14B'
dtype = 'bfloat16'
transformer_dtype = 'float8'
timestep_sample_method = 'logit_normal'

[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'

[optimizer]
type = 'adamw_optimi'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
eps = 1e-8
```

**dataset.toml**

```
resolutions = [512, 1024]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7

[[directory]]
path = '/workspace/diffusion-pipe/data/input'
num_repeats = 1
```

**Error message 1**

```
[2025-06-10 14:45:07,561] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=1 micro_batch_size=1
[2025-06-10 14:45:07,561] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2025-06-10 14:45:07,620] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=42 [0, 42) STAGE_PARAMS=153354240 (153.354M) TOTAL_PARAMS=153354240 (153.354M) UNIQUE_PARAMS=153354240 (153.354M)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 707, in <module>
[rank0]:     iterator = get_data_iterator_for_step(train_dataloader, model_engine)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 152, in get_data_iterator_for_step
[rank0]:     items = [next(dataloader_iter) for _ in range(num_micro_batches)]
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 152, in <listcomp>
[rank0]:     items = [next(dataloader_iter) for _ in range(num_micro_batches)]
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/utils/dataset.py", line 945, in __next__
[rank0]:     self.next_micro_batch = next(self.data)
[rank0]:                             ^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/utils/dataset.py", line 974, in _pull_batches_from_dataloader
[rank0]:     for batch in self.dataloader:
[rank0]:   File "/workspace/bcomfy/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
[rank0]:     self._iterator = self._get_iterator()
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/bcomfy/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
[rank0]:     return _MultiProcessingDataLoaderIter(self)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/bcomfy/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__
[rank0]:     w.start()
[rank0]:   File "/usr/lib/python3.11/multiprocessing/process.py", line 121, in start
[rank0]:     self._popen = self._Popen(self)
[rank0]:                   ^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
[rank0]:     return _default_context.get_context().Process._Popen(process_obj)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
[rank0]:     return Popen(process_obj)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
[rank0]:     super().__init__(process_obj)
[rank0]:   File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
[rank0]:     self._launch(process_obj)
[rank0]:   File "/usr/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
[rank0]:     reduction.dump(process_obj, fp)
[rank0]:   File "/usr/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
[rank0]:     ForkingPickler(file, protocol).dump(obj)
[rank0]: AttributeError: Can't pickle local object 'ModelOffloader.create_backward_hook.<locals>.backward_hook'
[rank0]:[W610 14:45:08.783797198 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank0]:[W610 14:45:10.028798222 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[2025-06-10 14:45:13,690] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 40388
[2025-06-10 14:45:13,690] [ERROR] [launch.py:325:sigkill_handler] ['/workspace/bcomfy/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'myconf/wan_14b_t2v.toml'] exits with return code = 1
```
**Error message 2**

```
[2025-06-10 14:54:05,044] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=1 micro_batch_size=1
[2025-06-10 14:54:05,044] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2025-06-10 14:54:05,104] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=42 [0, 42) STAGE_PARAMS=153354240 (153.354M) TOTAL_PARAMS=153354240 (153.354M) UNIQUE_PARAMS=153354240 (153.354M)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 707, in <module>
[rank0]:     iterator = get_data_iterator_for_step(train_dataloader, model_engine)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 152, in get_data_iterator_for_step
[rank0]:     items = [next(dataloader_iter) for _ in range(num_micro_batches)]
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 152, in <listcomp>
[rank0]:     items = [next(dataloader_iter) for _ in range(num_micro_batches)]
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/utils/dataset.py", line 945, in __next__
[rank0]:     self.next_micro_batch = next(self.data)
[rank0]:                             ^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/diffusion-pipe/utils/dataset.py", line 974, in _pull_batches_from_dataloader
[rank0]:     for batch in self.dataloader:
[rank0]:   File "/workspace/bcomfy/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
[rank0]:     self._iterator = self._get_iterator()
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/bcomfy/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
[rank0]:     return _MultiProcessingDataLoaderIter(self)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspace/bcomfy/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__
[rank0]:     w.start()
[rank0]:   File "/usr/lib/python3.11/multiprocessing/process.py", line 121, in start
[rank0]:     self._popen = self._Popen(self)
[rank0]:                   ^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
[rank0]:     return _default_context.get_context().Process._Popen(process_obj)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
[rank0]:     return Popen(process_obj)
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
[rank0]:     super().__init__(process_obj)
[rank0]:   File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
[rank0]:     self._launch(process_obj)
[rank0]:   File "/usr/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
[rank0]:     reduction.dump(process_obj, fp)
[rank0]:   File "/usr/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
[rank0]:     ForkingPickler(file, protocol).dump(obj)
[rank0]: TypeError: cannot pickle '_queue.SimpleQueue' object
[rank0]:[W610 14:54:06.038313557 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2025-06-10 14:54:08,492] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 44734
[2025-06-10 14:54:08,492] [ERROR] [launch.py:325:sigkill_handler] ['/workspace/bcomfy/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'myconf/wan_14b_t2v.toml'] exits with return code = 1
```

**Comment by arczewski** [comment]
Change first line in requirements.txt from deepspeed to deepspeed==0.16.9
then do installing requirements with pip again
It seems that there is some issue/breaking change with newest deepspeed.
If there are still issues then transformers==4.44.2.

@tdrussell Maybe it would be better to freeze versions in requirements.txt to prevent project breaking in the future due to dependencies?

**Comment by tdrussell** [comment]
I can confirm the problem is caused by Deepspeed 0.17.1. I pinned it to 0.17.0 which fixes the issue for me.

>Maybe it would be better to freeze versions in requirements.txt to prevent project breaking in the future due to dependencies?

I have avoided pinning all dependencies since this project relies on so much third party code. Old code is more likely to work with new versions of libraries, than new code is to work with old versions of libraries. It is tempting to say "let's just freeze every single transitive dependency to a known-working version", but then everything quickly starts becoming out of date, and now when you finally do need to update something, all sorts of things have a tendency to break all at once.

In all the time I have developed qlora-pipe and diffusion-pipe, there have only been a handful of times a dependency update broke something (this being one of those times), and usually it's easy to identify and fix or work around. I personally prefer this to pinning everything and risking things getting out of date.

With select dependencies like Deepspeed, I am okay with leaving them pinned to specific versions, since the code relies on the framework so much, and has some custom patching of internals.

**Comment by arczewski** [comment]
Make sense. In this case I wonder if this is some bug on deepspeed side and not actually a planned change. I don't see anything major between 17.0 and 17.1 - mostly some hot fixes/patches - https://github.com/deepspeedai/DeepSpeed/releases

**Comment by arczewski** [comment]
I take it back - this one is pretty big - https://github.com/deepspeedai/DeepSpeed/pull/7215

**Comment by yuhlearn** [comment]
> I can confirm the problem is caused by Deepspeed 0.17.1. I pinned it to 0.17.0 which fixes the issue for me.

Just want to confirm that this fix solved the issue for me. Thanks!
