### ISSUE TITLE
BlockSwap dosen't work

### ISSUE THREAD

**Issue by awsaws98** [tdrussell/diffusion-pipe#342]
It is so frustrated. No matter how I change my dataset and training config, it will immediately crash when I enable the block swap. Please help me...
WSL2, RAM:96G, SWAP:60G, 4090
dataset resolution: [-1,540],max:540 
ar_bucket:[256]
maxframe:81 

trainable params: 153,354,240 || all params: 14,442,255,424 || trainable%: 1.0618
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/rendanesktop/diffusion-pipe/train.py", line 496, in <module>
[rank0]:     model.enable_block_swap(blocks_to_swap)
[rank0]:   File "/home/rendanesktop/diffusion-pipe/models/wan/wan.py", line 396, in enable_block_swap
[rank0]:     self.prepare_block_swap_training()
[rank0]:   File "/home/rendanesktop/diffusion-pipe/models/wan/wan.py", line 402, in prepare_block_swap_training
[rank0]:     self.offloader.prepare_block_devices_before_forward()
[rank0]:   File "/home/rendanesktop/diffusion-pipe/utils/offloading.py", line 272, in prepare_block_devices_before_forward
[rank0]:     weights_to_device(b, torch.device('cpu'))  # make sure weights are on cpu
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/rendanesktop/diffusion-pipe/utils/offloading.py", line 119, in weights_to_device
[rank0]:     module.weight.data = module.weight.data.to(device, non_blocking=True)
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-08-01 17:11:20,585] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 64118
[2025-08-01 17:11:20,586] [ERROR] [launch.py:325:sigkill_handler] ['/home/rendanesktop/miniconda3wsl/envs/diffusion-pipe/bin/python3.12', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/wan22_main_example.toml'] exits with return code = 1

**Comment by ghost** [comment]
Block swap requires pipeline_stages = 1 did you set that any higher?

**Comment by tdrussell** [comment]
It looks like you might not have enough RAM. You can monitor your system memory usage as training starts and confirm if this is happening.

**Comment by awsaws98** [comment]
> It looks like you might not have enough RAM. You can monitor your system memory usage as training starts and confirm if this is happening.

Strange, I allocate 95G of RAM to WSL and increase the SWAP to 100G, blockswap=20,the maxium RAM usage from the training starts to the error is just 73%.

**Comment by awsaws98** [comment]
> Block swap requires pipeline_stages = 1 did you set that any higher?

yes, I double check , pipeline_stages = 1

**Comment by zdaar** [comment]
@awsaws98 Did you solve this ? I exported a working wsl vm to a new os (same system) and it broke for me. 60GB free, 20gb block swap and it will just fill my ram, stop and hold as it goes into swap, and crashes with an oom. Changing the block swap value does nothing. Giving wsl 100gb of swap and 64 gb of ram still crashes. Block swap 5 or 32, same behaviour. Rtx3090

**Comment by yunginvestor777-ctrl** [comment]
> [@awsaws98](https://github.com/awsaws98) Did you solve this ? I exported a working wsl vm to a new os (same system) and it broke for me. 60GB free, 20gb block swap and it will just fill my ram, stop and hold as it goes into swap, and crashes with an oom. Changing the block swap value does nothing. Giving wsl 100gb of swap and 64 gb of ram still crashes. Block swap 5 or 32, same behaviour. Rtx3090

Does it fill up your swap completely then crash? If so you may need a very large swap file to prevent OOM. I use a 800gb swap file on an NVME because I've seen swap fill up to over 200gb several times.

**Comment by zdaar** [comment]
I ported the same installation on several OS'es and here is what I found out : 

Windows 11 WSL2 : works
Windows 10 WSL2 : Memory leak will take ram to infinity and crash with an OOM (same exported w11 wsl VM, same wsl.conf)
Linux : works 

Anybody else on w10 with the issue ?

**Comment by yunginvestor777-ctrl** [comment]
> I ported the same installation on several OS'es and here is what I found out :
> 
> Windows 11 WSL2 : works Windows 10 WSL2 : Memory leak will take ram to infinity and crash with an OOM (same exported w11 wsl VM, same wsl.conf) Linux : works
> 
> Anybody else on w10 with the issue ?

I used to train on win 11 WSL but it always memory leaked and caused OOM even without block swap so I train on linux now.

**Comment by inver8** [comment]
Same problem. Windows 10, WSL 2, Ubuntu 24.04, 3090ti, 64gb ram. Offloading don't even move blocks to CPU. 
Maybe this error is due to the comfiui models?

[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/e/tools/ai/diffusion-pipe/train.py", line 500, in <module>
[rank0]:     model.enable_block_swap(blocks_to_swap)
[rank0]:   File "/mnt/e/tools/ai/diffusion-pipe/models/qwen_image.py", line 418, in enable_block_swap
[rank0]:     self.prepare_block_swap_training()
[rank0]:   File "/mnt/e/tools/ai/diffusion-pipe/models/qwen_image.py", line 424, in prepare_block_swap_training
[rank0]:     self.offloader.prepare_block_devices_before_forward()
[rank0]:   File "/mnt/e/tools/ai/diffusion-pipe/utils/offloading.py", line 272, in prepare_block_devices_before_forward
[rank0]:
[rank0]:   File "/mnt/e/tools/ai/diffusion-pipe/utils/offloading.py", line 119, in weights_to_device
[rank0]:
[rank0]: RuntimeError: CUDA error: out of memory

**Comment by tedbiv** [comment]
same here win10, wsl2, ubuntu 24.04, 4090, 128gb ram. if i comment out 'blocks_to_swap' in .toml file it runs, then dataset vid res has to be really low.

**Comment by tedbiv** [comment]
anybody got a workaround for this that doesn't involve disabling block swapping? crying in my beer...

**Comment by twoldogs** [comment]
same thing here,on wsl 2 win11. I set swap to 300G and 64G ram. it keep crashing and say cuda out of memory when the Vram never pass 20G. then I set rank to 16 and disable block swap to make it work. However, it still broke after few hours and says out of memory.

**Comment by sflores2** [comment]
> anybody got a workaround for this that doesn't involve disabling block swapping? crying in my beer...

I fixed it by commenting the non_blocking parameter in the gpu to cpu transfer lines, 
so, `.to("cpu")`  instead of `.to("cpu" , non_blocking=True) `, 
I had to modify offloading.py and unsloth_utils.py

**Comment by tedbiv** [comment]
> > anybody got a workaround for this that doesn't involve disabling block swapping? crying in my beer...
> 
> I fixed it by commenting the non_blocking parameter in the gpu to cpu transfer lines, so, `.to("cpu")` instead of `.to("cpu" , non_blocking=True) `, I had to modify offloading.py and unsloth_utils.py

thanks, i'll give that a try tomorrow.

**Comment by inver8** [comment]
> I fixed it by commenting the non_blocking parameter in the gpu to cpu transfer lines,
> so, `.to("cpu")` instead of `.to("cpu" , non_blocking=True) `,
> I had to modify offloading.py and unsloth_utils.py

It works 😀
Need to fix only this 3 lines:
In offloading.py at lines 76 and 119
in unsloth_utils.py at line 33

**Comment by tedbiv** [comment]
> > anybody got a workaround for this that doesn't involve disabling block swapping? crying in my beer...
> 
> I fixed it by commenting the non_blocking parameter in the gpu to cpu transfer lines, so, `.to("cpu")` instead of `.to("cpu" , non_blocking=True) `, I had to modify offloading.py and unsloth_utils.py

just tried it. it works. thanks so much. it's slow as hell, but it's training wan2.1 video dataset at 512x512. yay!

**Comment by alienzed** [comment]
@tdrussell 
does this make any sense to you? I've been banging my head against the wall with Windows 10+WSL for WAN training, just unable to get the WAN example going. Best I could do was disabling blocks to swap and training at (304,304,11) which for WAN is just nowhere near enough.
I'd also see my RAM (64GB) fill and hang there for 2-4 minutes before starting to train, but with anything above 304,304,11 or if I enabled blocks to swap, it just OOMs, sometimes after the RAM hangs and sometimes right before. My VRAM would typically go to 12gb usage and then crash... without blocks to swap it uses ~18gb of VRAM so there appears to be headroom there, I just can't seem to use it.

I completely rebuilt my system with the versions mentioned here... reinstalling flash attention right now hoping I did that wrong the first, time, but now I'm looking at these settings and wondering what they mean, what they'd change and if this is a bug and not a failure of my system.

next up I suppose I could try real Linux, but I have my env set up really well in Windows 10+WSL and HunyuanVideo training was working super well!

**Comment by alienzed** [comment]
> > > anybody got a workaround for this that doesn't involve disabling block swapping? crying in my beer...
> > 
> > 
> > I fixed it by commenting the non_blocking parameter in the gpu to cpu transfer lines, so, `.to("cpu")` instead of `.to("cpu" , non_blocking=True) `, I had to modify offloading.py and unsloth_utils.py
> 
> just tried it. it works. thanks so much. it's slow as hell, but it's training wan2.1 video dataset at 512x512. yay!

Could you give us a snapshot (in text) of your system specs, library versions, maybe the relevant parts of your config and dataset?
I'm having a really hard time getting to where you seem to be right now!

**Comment by alienzed** [comment]
So I got this working and took the liberty of compiling my system state to potentially help others achieve stable training.

```
System snapshot – WAN 14B LoRA on single GPU (WSL2 / Windows 10)

Host OS: Windows 10 + WSL2 (Ubuntu 22.04.5 LTS)
Kernel: 6.6.87.2-microsoft-standard-WSL2
GPU/Driver: NVIDIA GeForce RTX 4090, 581.57
CUDA toolkit: 12.8 (nvcc) | CUDA_HOME=/usr/local/cuda-12.8
Python: 3.12.12 (conda env: dp-clean)
RAM/Swap: 62 Gi / 200 Gi (NVMe-backed)

Torch stack: torch 2.9.0+cu128 (CUDA 12.8), torchvision 0.24.0+cu128, torchaudio 2.9.0+cu128
Libraries: flash-attn 2.8.3 (built from source), deepspeed 0.17.0,
           transformers 4.45.2, diffusers 0.31.0, datasets 3.4.1, peft 0.17.1
**FlashAttention SASS: sm_89**
Build-time env: FLASH_ATTN_CUDA_ARCHS=89, MAX_JOBS=2

Allocator: default (PYTORCH_CUDA_ALLOC_CONF unset)
CPU offload: synchronous (DP_CPU_OFFLOAD_ASYNC unset)
BlockSwap: disabled
Training: WAN 14B LoRA 512×512×33, activation_checkpointing=unsloth

Repo: https://github.com/tdrussell/diffusion-pipe
Commit: 2ce6de03444ca547006f3726a7aa284ddc10c4dd

```

It's hard to tell sometimes if a single change was really the solution, but as far as I can tell, what allowed me to train with more than 304x304x8, now doing, 512,512,33, was compiling flash attention for python, torch and my video card, the 4090, with sm_89.
previously it was giving me generic versions (sm_80 and sm_90 I believe) and I couldn't NOT OOM.
Compiling flash attention for my card took ~45 minutes

I can't use blockswap even with the code modifications listed above, but training runs and runs well, same speed as Hunyuan as far as I can tell :)
