### ISSUE TITLE
WAN 2.2 training attempt: "cannot import name 'PreTrainedModel' from 'transformers'"

### ISSUE THREAD

**Issue by gituser123456789000** [tdrussell/diffusion-pipe#383]
**Full code:**
NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config examples/wan22low.toml
[2025-08-15 01:22:03,399] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-15 01:22:05,026] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-08-15 01:22:05,026] [INFO] [runner.py:605:main] cmd = /home/username/miniconda3/envs/diffusion-pipe/bin/python3.12 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config examples/wan22low.toml
[2025-08-15 01:22:05,741] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-15 01:22:07,396] [INFO] [launch.py:139:main] 0 NCCL_IB_DISABLE=1
[2025-08-15 01:22:07,396] [INFO] [launch.py:139:main] 0 NCCL_P2P_DISABLE=1
[2025-08-15 01:22:07,396] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2025-08-15 01:22:07,396] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2025-08-15 01:22:07,396] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2025-08-15 01:22:07,396] [INFO] [launch.py:164:main] dist_world_size=1
[2025-08-15 01:22:07,396] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2025-08-15 01:22:07,397] [INFO] [launch.py:256:main] process 1163 spawned with command: ['/home/username/miniconda3/envs/diffusion-pipe/bin/python3.12', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/wan22low.toml']
[2025-08-15 01:22:08,403] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/username/diffusion-pipe/train.py", line 30, in <module>
    from utils.patches import apply_patches
  File "/home/username/diffusion-pipe/utils/patches.py", line 9, in <module>
    import peft
  File "/home/username/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/peft/__init__.py", line 17, in <module>
    from .auto import (
  File "/home/username/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/peft/auto.py", line 31, in <module>
    from .config import PeftConfig
  File "/home/username/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/peft/config.py", line 24, in <module>    from .utils import CONFIG_NAME, PeftType, TaskType
  File "/home/username/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/peft/utils/__init__.py", line 17, in <module>
    from .other import (
  File "/home/username/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/peft/utils/other.py", line 36, in <module>
    from transformers import PreTrainedModel
ImportError: cannot import name 'PreTrainedModel' from 'transformers' (/home/username/miniconda3/envs/diffusion-pipe/lib/python3.12/site-packages/transformers/__init__.py)
[2025-08-15 01:22:12,398] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 1163
[2025-08-15 01:22:12,398] [ERROR] [launch.py:325:sigkill_handler] ['/home/username/miniconda3/envs/diffusion-pipe/bin/python3.12', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/wan22low.toml'] exits with return code = 1

**config.toml** actually named wan22low.toml
output_dir = 'data/output'
dataset = 'examples/dataset.toml'

epochs = 20
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 2
gradient_clipping = 1
warmup_steps = 10

eval_every_n_epochs = 0
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

save_every_n_epochs = 1
#checkpoint_every_n_minutes = 60
activation_checkpointing = 'unsloth'
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 10
video_clip_mode = 'single_beginning'
blocks_to_swap = 8

[model]
type = 'wan'
ckpt_path = 'models/wan/Wan2.2-T2V-A14B'
transformer_path = 'models/wan/low_noise_model/wan2.2_t2v_low_noise_14B_fp16.safetensors'
llm_path = 'models/wan/Wan2.2-T2V-A14B/umt5_xxl_fp16.safetensors'
dtype = 'bfloat16'
transformer_dtype = 'float8'

min_t = 0
max_t = 0.875

[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'

[optimizer]
type = 'AdamW8bitKahan'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
stabilize = false

**dataset.toml**
resolutions = [512]
shuffle_caption = true
keep_tokens = 0

enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
min_ar_bucket_reso = 256
max_ar_bucket_reso = 1024
bucket_reso_steps = 64
num_ar_buckets = 7

frame_buckets = [1]

[[directory]] # Image Directory
  path = "/home/username/diffusion-pipe/data/input/dataset" # <<< CHECK THIS PATH!
  caption_extension = ".txt"
  batch_size = 1
  num_repeats = 10

**Comment by gituser123456789000** [comment]
Google AI, which could very easily be wrong, said to upgrade transformers and to run:
pip install --upgrade transformers

it uninstalled 4.55.0 and installed 4.55.2

Same error, that didn't fix it

**Comment by gituser123456789000** [comment]
I uninstalled torch 2.8.0 and installed 2.4.1, because earlier in installation of diffusion pipe it had red text for torchvision and torchaudio saying they require 2.4.1 but I have 2.8.0 which is incompatible

during that install of torch 2.4.1, at the end it had new red text that optimum-quanto 0.2.7 requires torch 2.6.0 but I had torch 2.4.1 which is incompatible

I ran the training lines anyway
"NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config examples/wan22low.toml"
..in my case.. and got a new error:

FileNotFoundError: No such file or directory: models/wan/low_noise_model/wan2.2_t2v_low_noise_14B_fp16.safetensors

So I see in my config.toml file (named wan22low.toml) I have a directory typo for my transformer_path
should be models/wan/Wan2.2-T2V-A14B/etc
but I only had models/wan/etc

**Comment by gituser123456789000** [comment]
Got much further after those changes.. error now, after many progress bars for caching etc, is out of memory error.. so I likely need to ditch the FP16 models and train on FP8/Q8. Will try that next

**Comment by gituser123456789000** [comment]
tried training on FP8 models.. got an error saying scaled models aren't supported
tried training on Q8 .gguf models... error safetensors_rust.SafetensorError: Error while deserializing header: header too large

now looking for FP8 non-scaled models.. does that exist...

**Comment by gituser123456789000** [comment]
Switched back to FP16 models..
changed blocks_to_swap from 8 to 32...
doesn't work. still out of memory error

ending portion of the error code:
WARNING:datasets.arrow_dataset:num_proc must be <= 3. Reducing num_proc to 3 for dataset of size 3.
caching text embeddings: [0.5, 1]
Map: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 1687.17 examples/s]
num_proc must be <= 2. Reducing num_proc to 2 for dataset of size 2.
WARNING:datasets.arrow_dataset:num_proc must be <= 2. Reducing num_proc to 2 for dataset of size 2.
num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
WARNING:datasets.arrow_dataset:num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
trainable params: 153,354,240 || all params: 14,441,845,824 || trainable%: 1.0619
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/username/diffusion-pipe/train.py", line 500, in <module>
[rank0]:     model.enable_block_swap(blocks_to_swap)
[rank0]:   File "/home/username/diffusion-pipe/models/wan/wan.py", line 397, in enable_block_swap
[rank0]:     self.prepare_block_swap_training()
[rank0]:   File "/home/username/diffusion-pipe/models/wan/wan.py", line 403, in prepare_block_swap_training
[rank0]:     self.offloader.prepare_block_devices_before_forward()
[rank0]:   File "/home/username/diffusion-pipe/utils/offloading.py", line 272, in prepare_block_devices_before_forward
[rank0]:     weights_to_device(b, torch.device('cpu'))  # make sure weights are on cpu
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/username/diffusion-pipe/utils/offloading.py", line 119, in weights_to_device
[rank0]:     module.weight.data = module.weight.data.to(device, non_blocking=True)
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: out of memory
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-08-15 03:45:27,358] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 11648
[2025-08-15 03:45:27,358] [ERROR] [launch.py:325:sigkill_handler] ['/home/username/miniconda3/envs/diffusion-pipe/bin/python3.12', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/wan22low.toml'] exits with return code = 1

**Comment by gituser123456789000** [comment]
uninstalled torch (2.4.1)
installed torch 2.8.0 which I had initially.. didn't go through any caching and had the old error of :
ImportError: cannot import name 'PreTrainedModel' from 'transformers'

**Comment by gituser123456789000** [comment]
uninstalled torch (2.8.0)
installed torch 2.4.1
changed blocks_to_swap from 32 to 64
failed because maximum blocks to swap is 38
changed blocks_to_swap back to 32

**Comment by gituser123456789000** [comment]
I switched to the default main_example.toml
made the most basic changes required for WAN like adding min_t and max_t

somehow the default with minor adjustments is working.. not sure which is the cause.. could be adamw_optimi instead of AdamW8bitKahan
or activate_checkpointing = true instead of 'unsloth'
or steps per print 1 instead of 10
or gradient accumulation steps 1 instead of 2
no idea which was causing out of memory error or something else

Here's what's running for me:
```
# Output path for training runs. Each training run makes a new directory in here.
output_dir = 'data/output'

# Dataset config file.
dataset = 'examples/dataset.toml'
# You can have separate eval datasets. Give them a name for Tensorboard metrics.
# eval_datasets = [
#     {name = 'something', config = 'path/to/eval_dataset.toml'},
# ]

# training settings

# I usually set this to a really high value because I don't know how long I want to train.
epochs = 20
# Batch size of a single forward/backward pass for one GPU.
micro_batch_size_per_gpu = 1
# For mixed video / image training, you can have a different batch size for images.
#image_micro_batch_size_per_gpu = 4
# Pipeline parallelism degree. A single instance of the model is divided across this many GPUs.
pipeline_stages = 1
# Number of micro-batches sent through the pipeline for each training step.
# If pipeline_stages > 1, a higher GAS means better GPU utilization due to smaller pipeline bubbles (where GPUs aren't overlapping computation).
gradient_accumulation_steps = 1
# Grad norm clipping.
gradient_clipping = 1.0
# Learning rate warmup.
warmup_steps = 100
# Force the learning rate to be this value, regardless of what the optimizer or anything else says.
# Can be used to change learning rate even when resuming from checkpoint.
#force_constant_lr = 1e-5

# Block swapping is supported for Wan, HunyuanVideo, Flux, and Chroma. This value controls the number
# of blocks kept offloaded to RAM. Increasing it lowers VRAM use, but has a performance penalty. The
# exactly performance penalty depends on the model and the type of training you are doing (e.g. images vs video).
# Block swapping only works for LoRA training, and requires pipeline_stages=1.
#blocks_to_swap = 20

# eval settings

eval_every_n_epochs = 1
eval_before_first_step = true
# Might want to set these lower for eval so that less images get dropped (eval dataset size is usually much smaller than training set).
# Each size bucket of images/videos is rounded down to the nearest multiple of the global batch size, so higher global batch size means
# more dropped images. Usually doesn't matter for training but the eval set is much smaller so it can matter.
eval_micro_batch_size_per_gpu = 1
# Batch size for images when doing mixed image / video training. Will be micro_batch_size_per_gpu if not set.
#image_eval_micro_batch_size_per_gpu = 4
eval_gradient_accumulation_steps = 1
# If using block swap, you can disable it for eval. Eval uses less memory, so depending on block swapping amount you can maybe get away with
# doing this, and then eval is much faster.
#disable_block_swap_for_eval = true

# misc settings

# Probably want to set this a bit higher if you have a smaller dataset so you don't end up with a million saved models.
save_every_n_epochs = 1
# Can checkpoint the training state every n number of epochs or minutes. Set only one of these. You can resume from checkpoints using the --resume_from_checkpoint flag.
#checkpoint_every_n_epochs = 1
#checkpoint_every_n_minutes = 120
# Always set to true unless you have a huge amount of VRAM.
# This can also be 'unsloth' to reduce VRAM even more, with a slight performance hit.
activation_checkpointing = true
# Use reentrant activation checkpointing method (set this in addition to `activation_checkpointing`). Might be required for some models
# when using pipeline parallelism (pipeline_stages>1). Otherwise recommended to not use it.
#reentrant_activation_checkpointing = true

# Controls how Deepspeed decides how to divide layers across GPUs. Probably don't change this.
partition_method = 'parameters'
# Alternatively you can use 'manual' in combination with partition_split, which specifies the split points for dividing
# layers between GPUs. For example, with two GPUs, partition_split=[10] puts layers 0-9 on GPU 0, and the rest on GPU 1.
# With three GPUs, partition_split=[10, 20] puts layers 0-9 on GPU 0, layers 10-19 on GPU 1, and the rest on GPU 2.
# Length of partition_split must be pipeline_stages-1.
#partition_split = [N]

# dtype for saving the LoRA or model, if different from training dtype
save_dtype = 'bfloat16'
# Batch size for caching latents and text embeddings. Increasing can lead to higher GPU utilization during caching phase but uses more memory.
caching_batch_size = 1

# Number of parallel processes to use in map() calls when caching the dataset. Defaults to min(8, num_cpu_cores) if unset.
# If you have a lot of cores and multiple GPUs, raising this can increase throughput of caching, but it may use more memory,
# especially for video data.
#map_num_proc = 32

# Use torch.compile on the model. Can speed up training throughput by a decent amount. Not tested on all models.
#compile = true

# How often deepspeed logs to console.
steps_per_print = 1
# How to extract video clips for training from a single input video file.
# The video file is first assigned to one of the configured frame buckets, but then we must extract one or more clips of exactly the right
# number of frames for that bucket.
# single_beginning: one clip starting at the beginning of the video
# single_middle: one clip from the middle of the video (cutting off the start and end equally)
# multiple_overlapping: extract the minimum number of clips to cover the full range of the video. They might overlap some.
# default is single_beginning
video_clip_mode = 'single_beginning'

# This is how you configure HunyuanVideo. Other models will be different. See docs/supported_models.md for
# details on the configuration and options for each model.
[model]
type = 'wan'
# Can load HunyuanVideo entirely from the ckpt path set up for the official inference scripts.
ckpt_path = 'models/wan/Wan2.2-T2V-A14B'
# Or you can load it by pointing to all the ComfyUI files.
transformer_path = 'models/wan/Wan2.2-T2V-A14B/low_noise_model/wan2.2_t2v_low_noise_14B_fp16.safetensors'
#vae_path = '/data2/imagegen_models/hunyuan_video_comfyui/hunyuan_video_vae_bf16.safetensors'
llm_path = 'models/wan/Wan2.2-T2V-A14B/umt5_xxl_fp16.safetensors'
#clip_path = '/data2/imagegen_models/hunyuan_video_comfyui/clip-vit-large-patch14'
# Base dtype used for all models.
dtype = 'bfloat16'
# Hunyuan Video supports fp8 for the transformer when training LoRA.
transformer_dtype = 'float8'
# How to sample timesteps to train on. Can be logit_normal or uniform.
timestep_sample_method = 'logit_normal'
min_t = 0
max_t = 0.875

# For models that support full fine tuning, simply delete or comment out the [adapter] table to FFT.
[adapter]
type = 'lora'
rank = 32
# Dtype for the LoRA weights you are training.
dtype = 'bfloat16'
# You can initialize the lora weights from a previously trained lora.
#init_from_existing = '/data/diffusion_pipe_training_runs/something/epoch50'
# Experimental. Can fuse LoRAs into the base weights before training. Right now only for Flux.
#fuse_adapters = [
#    {path = '/data2/imagegen_models/loras/some_lora.safetensors', weight = 1.0}
#]

[optimizer]
# AdamW from the optimi library is a good default since it automatically uses Kahan summation when training bfloat16 weights.
# Look at train.py for other options. You could also easily edit the file and add your own.
type = 'adamw_optimi'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
eps = 1e-8

# Can use this optimizer for a bit less memory usage.
# [optimizer]
# type = 'AdamW8bitKahan'
# lr = 2e-5
# betas = [0.9, 0.99]
# weight_decay = 0.01
# stabilize = false

# Automagic optimizer from AI-Toolkit.
# In my experience, this gives slightly worse results than AdamW with a properly tuned LR, but you can try it.

# [optimizer]
# type = 'automagic'
# weight_decay = 0.01

# Any optimizer not explicitly supported will be dynamically loaded from the pytorch-optimizer library.
# [optimizer]
# type = 'Prodigy'
# lr = 1
# betas = [0.9, 0.99]
# weight_decay = 0.01

[monitoring]
# Set to true and fill in these fields to enable wandb
enable_wandb = false
wandb_api_key = ''
wandb_tracker_name = ''
wandb_run_name = ''
```

**changes I made from the default main_example config file:**
changed my paths obviously.. for dataset
dropped epochs from 100 to 20
commented out using # the checkpoint every 120 minutes line.. I don't want or need checkpoints if they take up space
changed model section > type = 'wan' instead of hunyuan-video
removed the # for ckpt_path and added my path there ckpt_path = 'models/wan/Wan2.2-T2V-A14B'
changed to my WAN transformer path and llm path
commented out (using #) the vae path and clip path (may need vae path I would have guessed, but other WAN configs I see it commented out, so we'll see)
added min_t = 0 max_t = 0.875 and the high noise config will need to be min_t = 0.875 max_t = 1

**Comment by gituser123456789000** [comment]
Follow-up.. it worked and results were surprisingly very good. Even using the low model trained lora on both high and low in the workflow looked good, but I'm sure low and high loras will look even better

**Comment by gituser123456789000** [comment]
So now if we want to train for maximum resolution outputs only... what should that dataset file look like?
Max res for WAN 2.2 is 704x1280 or vice versa.

```
resolutions = [[704, 1280]]
shuffle_caption = true
keep_tokens = 0

enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
min_ar_bucket_reso = 704
max_ar_bucket_reso = 1280
bucket_reso_steps = 64
num_ar_buckets = 7

frame_buckets = [1]

[[directory]] # Image Directory
  path = "/home/username/diffusion-pipe/data/input/dataset" # <<< CHECK THIS PATH!
  caption_extension = ".txt"
  batch_size = 1
  num_repeats = 10
```

Would this be correct to train the lora for specifically doing max res portrait outputs at 704x1280?
*I put that resolution as [704, 1280] in an extra set of brackets... and I'm sure [[704, 1280], [1280, 704[] would train both portrait and landscape.. that seems easy to understand

*min_ar_bucket_reso and max_ar_bucket_reso.. made these 704 and 1280, if that's all I want the lora to output, that seems like what that should be set to

*min_ar and max_ar.... these could both be 0.55? (704/1280 = 0.55).. or for portrait and landscape it would be 0.55 and 1.818181818181818 which isn't very clean

*bucket_reso_steps and num_ar_buckets could be commented out? and if not commented out, and left at 64 for resolution steps.. should num_ar_buckets be 10? since 704 through 1280 is 10 multiples of 64 (including both ends).. 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280.. or should it be 9?, or 8?

Going to attempt only training toward 704x1280 portrait and see what happens. Hopefully training would be much faster also, and fit into VRAM easier by only training 1 resolution instead of many variations

**Comment by gituser123456789000** [comment]
currently attempting this:

```
resolutions = [[704, 1280]]
shuffle_caption = true
keep_tokens = 0

enable_ar_bucket = false
#min_ar = 0.5
#max_ar = 2.0
#min_ar_bucket_reso = 704
#max_ar_bucket_reso = 1280
#bucket_reso_steps = 64
#num_ar_buckets = 7

frame_buckets = [1]

[[directory]] # Image Directory
  path = "/home/username/diffusion-pipe/data/input/dataset" # <<< CHECK THIS PATH!
  caption_extension = ".txt"
  batch_size = 1
  num_repeats = 10
```

resolution only 704x1280..
turned ar buckets off with "false" and commented out all of the settings to be sure that they're all skipped

it's running on 4090 24GB VRAM 96GB RAM.. looks like it would likely run with 64GB RAM also. Iteration time is about 5 seconds per step.. at least for 25 images and 10 repeats

**Comment by gituser123456789000** [comment]
The above training on max res only worked... but it still works fine on lower res too, so?? Tested on 704x1280 and tested on 480p even though it wasn't trained for it or bucketed at all, and it still looks fine on 480p. Not sure why that is. I was thinking and maybe hoping if you only trained on 1 res then training might be much faster and file size much smaller, but file size is the same as when trained at 512 with buckets

**Comment by tdrussell** [comment]
The config isn't doing what you think it is. You should carefully read the comments in the example dataset configs.

```
shuffle_caption = true
keep_tokens = 0
#min_ar_bucket_reso = 704
#max_ar_bucket_reso = 1280
#bucket_reso_steps = 64
batch_size = 1
```
None of these are options the code supports. I think you have just taken them from sd-scripts.

>enable_ar_bucket = false

This will completely disable aspect ratio bucketing. It will make it so there is always 1 bucket, and that bucket has an AR of 1. I.e. single square bucket.

>resolutions = [[704, 1280]]

As the comment in the example states, this is the same thing as passing resolutions=[sqrt(704*1280)]. It's not using the width and height, this is just a convenient way to specify a resolution area.

If you want to train on exact hardcoded size buckets, see cosmos_dataset.toml as an example. This is probably what you're trying to do.

**Comment by gituser123456789000** [comment]
Ok, I looked at the cosmos.toml

I'll try that next. Currently running a Rank 96 test, I know it should capture more details from the training images (whether good or bad.. bad if they're lower quality, which my test dataset is not the greatest quality).. and lora file size will be bigger, but I still want to see how it looks with WAN 2.2. Planned to try Rank 128, but it was too much for my settings and available hardware

I don't really understand everything you explained.
So what resolution(s) did I end up training with
resolutions = [[704, 1280]]
enable_ar_bucket = false

You say it only trained a square 1:1 aspect ratio? Of what resolution(s)?

sqrt(704*1280) you wrote comes to 949
So I trained just 949x949?

But 704x1280 and 480p generations in ComyUI still look good with those config settings

**Comment by tdrussell** [comment]
>So I trained just 949x949?

Yes. It will print all the size buckets it is caching (or loading from cache), so you can see this in the terminal.

It would have cropped all your training data to square, which isn't good, but if your subjects are all centered maybe it doesn't matter that much. And these models are relatively robust to different resolutions. They can do cross-resolution and cross-aspect-ratio learning pretty well.

**Comment by inver8** [comment]
> changed blocks_to_swap from 8 to 32...
> doesn't work. still out of memory error

I think block swap is broken, at least on wsl.

**Comment by gituser123456789000** [comment]
testing the cosmos_dataset format now with just 1 resolution. Training time looks similar, likely a few tenths of a second longer on average.. nearing mid-5sec per step

`size_buckets = [
    [704, 1280, 1],
]

[[directory]]
path = '/home/username/diffusion-pipe/data/input/dataset'
num_repeats = 10`

will report back later how it performs with different resolution generations.. really just interesting in how it compares at max resolution, but curious how it performs overall too if only trained on 1 resolution

Slower speed may be from VRAM spillover... Dedicated GPU memory shows 23.5/24.0, but GPU Memory is ~24.4/70.8.. so some spillover into regular RAM it seems at this training res with my hardware (and other apps open)

**Comment by gituser123456789000** [comment]
follow-up on train 1 single resolution at 1 single aspect ratio..
It doesn't seem any better. If it's better at the 1 resolution and aspect ratio, it seems to be a minimal difference.
It still works at other resolutions. Same aspect ratio at lower res is still decent looking, but maybe not as good... not so far off though.
Different aspect ratios, like doing landscape instead of the portrait I trained for, that looks to have noticeable drop-off in character likeness but still gets the general concept.
So I see no benefit to training 1 resolution/aspect ratio yet. I'll run some more comparisons, but so far it doesn't look noticeably better at what it was trained so specifically for.

That's also only testing 1 lora trained on the Low noise model though and using the Low model lora for both Low and High in the workflow. Maybe it would make a more noticeable difference with a separate High model lora. I'll run that now.

**Comment by gituser123456789000** [comment]
training and adding High noise lora to the workflow, it recreates the original images with very minimal differences (when tested on creating 1 frame with the same prompts as the training data).. and there's very little variety between seeds

So that shows accuracy to the original dataset is excellent.. but need to test if that means it could be very stiff for other prompts or for video. Testing now.

If it's from overtraining.. being 5000 steps each for Low and High loras.. and Rank 96... that should be no issues, since I saved epochs every 250 steps for each.

One 33 frame video tested so far and it's very accurate to the original image when using the same prompt.. and motion is still there, it doesn't seem stiff as far as motion. Testing another like this, just to verify again that it recreates the original dataset very accurately.. then will run tests on changing the prompts with different details or colors to see if it's completely stiff to the originals or not.. If yes, that's unfortunate, if it would only reproduce the originals and make video from that.. If no, if it's still flexible.. or if another epoch is flexible.. then this is a very impressive training outcome.

**Comment by gituser123456789000** [comment]
It's completely flexible in changing details while keeping everything else looking very near the original dataset. For example, if the original dataset has a person with wearing a red shirt and yellow pants.. you change it to purple shirt and green pants using the original prompt and the result is very very near the original, but with the changes made. Or change shirt to sweater, pants to shorts.. same. It makes very very near the original while making the changes that were made in the prompt.

Lastly need to test how it does with a completely different prompt that has nothing to do with the original dataset and image descriptions.

There's a brand new Google AI that is this, but even more completely true and real looking to the original image..
'Nano-Banana' (possibly aka new model called "genpix")
"soon end of LORAs"

https://www.instagram.com/evolving.ai/p/DNgF7AtIB6R/?img_index=1

**Comment by gituser123456789000** [comment]
> There's a brand new Google AI that is this, but even more completely true and real looking to the original image.. 'Nano-Banana' (possibly aka new model called "genpix") "soon end of LORAs"
> 
> https://www.instagram.com/evolving.ai/p/DNgF7AtIB6R/?img_index=1

![Image](https://github.com/user-attachments/assets/730931ce-1218-461e-8ee6-ce43eddd365f)

![Image](https://github.com/user-attachments/assets/4fac13c8-ea7e-4c87-9f7b-0477223c34ba)

![Image](https://github.com/user-attachments/assets/ce4d8e84-b6d9-4508-a3fb-e2e7127ead7b)

![Image](https://github.com/user-attachments/assets/c7c57a91-2f93-402d-a57b-69ff5a472499)

![Image](https://github.com/user-attachments/assets/8a310474-2cd9-457f-b586-4db3e89cb165)

![Image](https://github.com/user-attachments/assets/58494224-0164-410f-929f-d2a5c9ed86e0)

![Image](https://github.com/user-attachments/assets/d7e85873-48af-44b0-99e4-f81c1237ad25)

![Image](https://github.com/user-attachments/assets/c06aef9e-5677-4873-b1ef-5af34545f442)

![Image](https://github.com/user-attachments/assets/687f10ea-3882-4b55-9e41-f11664bfe88a)

**Comment by gituser123456789000** [comment]
> If you want to train on exact hardcoded size buckets, see cosmos_dataset.toml as an example. This is probably what you're trying to do.

Going to retrain on all of your default cosmos resolutions.. including landscape and the 960 resolution variations.

I wonder why it's 960 and not 992 which would be (1280+704)/2.. or 1024, but no big deal. I see 960 mentioned elsewhere also as supposedly working best for 1:1 aspect ratio.

Single resolution with Rank 96 I said had great likeness and recreation of the original training data, which was true, but original training data had compression artifacts, etc.. not legit high resolution images.

Going to retry on lower Ranks. I noticed what I previously trained at just 512 resolution and Rank 32 (but only Low noise lora).. the likeness wasn't as good, but fine details were much better. It hadn't learned the likeness as well, but it also didn't learn the quality issues of the dataset images. I'll have to train several times and find the right mix of resolution and Rank. I'm thinking Rank 32 will win out and 64 and 96+ should be reserved for only very high quality datasets that you actually want to learn every detail, every pixel.

So running Rank 32 and Rank 64 runs on low and high noise models... will take a day or two.

I recaptioned images with Florence 2 Flux Large in ComfyUI and made manual edits to fix errors or add any missing details.
Previously I had WD14 based captioning through kohya_ss with some manual fixes

**Comment by gituser123456789000** [comment]
I couldn't get training to run again...
I messed with the settings.. removing resolutions, lowering resolutions, cut repeats in half..
I made a new dataset folder with only 3 images...
I turned PC off and on
I restarted PC
I moved display cable from GPU to motherboard (this frees up VRAM on your main GPU if your CPU has integrated graphics)
I kept getting CUDA crashes.. I would see VRAM spike over 24GB in Task Manager and instacrash before training started

I remembered before I started this round of training, I commented out `# activation_checkpointing = true`
That turned out to be the issue. I should not have `#`ed it
It seems this is necessary to keep VRAM in check, or at least stop it from spiking

So with checkpointing back enabled.. and with display running on CPU/motherboard instead of GPU.. training is only using 20.9/24.0 Dedicated GPU memory and 21.0/70.8GB GPU memory (with half of regular RAM being 'Shared')

Display running on CPU's iGPU is using 1.0/2.0GB Dedicated (this actually uses your system RAM as its 'VRAM' and you should be able to adjust it in BIOS. Stock may be a lesser amount like 512MB) and 1.4/48.8GB GPU Memory. So I may have still been below 24 GB VRAM usage even without switching display cable from GPU to CPU/motherboard, but this is still a good recommendation for freeing up VRAM and either being able to run things at the limit without crashing, or not have VRAM spill over and things end up taking longer.

Now that I'm not spilling over my steps are averaging about 4.4 seconds (varies between 4.2s - 4.9s) each instead of around 5.5 seconds in my last attempt.. around 20% faster.. and that's with 28 images instead of 25 images and training at 2 resolutions instead of 1 (although I'm not sure the resolutions make a time difference or not, the ~10% bigger dataset should)

training Rank 32 at max res portrait and landscape 704x1280 and 1280x704 with cosmos_dataset format

**Comment by BenDes21** [comment]
> It's completely flexible in changing details while keeping everything else looking very near the original dataset. For example, if the original dataset has a person with wearing a red shirt and yellow pants.. you change it to purple shirt and green pants using the original prompt and the result is very very near the original, but with the changes made. Or change shirt to sweater, pants to shorts.. same. It makes very very near the original while making the changes that were made in the prompt.
> 
> Lastly need to test how it does with a completely different prompt that has nothing to do with the original dataset and image descriptions.
> 
> There's a brand new Google AI that is this, but even more completely true and real looking to the original image.. 'Nano-Banana' (possibly aka new model called "genpix") "soon end of LORAs"
> 
> https://www.instagram.com/evolving.ai/p/DNgF7AtIB6R/?img_index=1

Hello, how train both high and low noise models at the same time ?

**Comment by gituser123456789000** [comment]
> > It's completely flexible in changing details while keeping everything else looking very near the original dataset. For example, if the original dataset has a person with wearing a red shirt and yellow pants.. you change it to purple shirt and green pants using the original prompt and the result is very very near the original, but with the changes made. Or change shirt to sweater, pants to shorts.. same. It makes very very near the original while making the changes that were made in the prompt.
> > Lastly need to test how it does with a completely different prompt that has nothing to do with the original dataset and image descriptions.
> > There's a brand new Google AI that is this, but even more completely true and real looking to the original image.. 'Nano-Banana' (possibly aka new model called "genpix") "soon end of LORAs"
> > https://www.instagram.com/evolving.ai/p/DNgF7AtIB6R/?img_index=1
> 
> Hello, how train both high and low noise models at the same time ?

I'm sure you don't and you'd need double the VRAM etc to do it anyway, or have to train at much lower resolution. You train them separately... doesn't matter what order you train them, but obviously will matter where you use them in your workflow, so make sure you label them correctly.

**Comment by gituser123456789000** [comment]
@tdrussell 
Would you train pictures and video of a character together? Or does it make more sense to train them in 2 separate loras?

And if training together, how would that look?... Assuming video has to be trained at a lower resolution to fit in VRAM.

For example if this is the dataset toml used to train on photos only:
```
# Cosmos will only work properly with a fixed set of resolutions and frame lengths. Rather than setting up flexible aspect ratio buckets
# and target resolutions, for this model you must directly specify the desired final size_buckets. This is for image training. For video
# training, it seems you must use the full 121 frame length at these resolutions, which I can't even test because it would take too much
# VRAM.
size_buckets = [
    [960, 960, 1],
    [1280, 704, 1],
    [704, 1280, 1],
]

[[directory]]
path = '/home/username/diffusion-pipe/data/input/dataset'
num_repeats = 10
```

Would training on video also look like:
```
# Cosmos will only work properly with a fixed set of resolutions and frame lengths. Rather than setting up flexible aspect ratio buckets
# and target resolutions, for this model you must directly specify the desired final size_buckets. This is for image training. For video
# training, it seems you must use the full 121 frame length at these resolutions, which I can't even test because it would take too much
# VRAM.
size_buckets = [
    [960, 960, 1],
    [1280, 704, 1],
    [704, 1280, 1],
    [456, 256, 81],
    [256, 456, 81],
]

[[directory]]
path = '/home/username/diffusion-pipe/data/input/dataset'
num_repeats = 10
```

Would that be the right way to do it? Would those "[456, 256, 81], [256, 456, 81]," lines train video clips at lower resolution to fit in VRAM while still training single frame images at full 1280x704 resolution?

I see the notes, but that seems to refer to HunyuanVideo 121 frames instead of WAN 2.2 81 frames... and I assume video training could fit in VRAM if the resolution was low enough. Just wondering what the proper format would be so I can test it.

**Comment by gituser123456789000** [comment]
Uninstalled everything, because I don't know how to update it. I used git pull, but it didn't work. I don't know where I'm supposed to do that...

Anyway, did a fresh install to try Z Image Turbo and got the same error again.. cannot import name 'PreTrainedModel' from 'transformers'
