### ISSUE TITLE
Getting NCCL shared memory error when trying to train on DGX Spark.

### ISSUE THREAD

**Issue by stierma1** [tdrussell/diffusion-pipe#446]
I am trying to train on the DGX spark.  I am getting the following error when I start the trainer with BNB_CUDA_VERSION=130 NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" NCCL_SHM_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config configs/test.toml .  Can someone help inspect? I am a little out of my depth on this. I am training a Wan 2.2 low noise T2V model.  I based it off a configuration that I know works on my other systems.
```

WARNING: BNB_CUDA_VERSION=130 environment variable detected; loading libbitsandbytes_cuda130.so.
This can be used to load a bitsandbytes version built with a CUDA version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=

loading comfyui repacked umt5 safetensors model...
Unmapped keys (usually safe to ignore): ['spiece_model']
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/stier020/code/diffusion-pipe/train.py", line 449, in <module>
[rank0]:     dataset_manager.cache()
[rank0]:   File "/home/stier020/code/diffusion-pipe/utils/dataset.py", line 1027, in cache
[rank0]:     torch.distributed.broadcast_object_list(queue, src=0, group=dist.get_world_group())
[rank0]:   File "/home/stier020/code/diffusion-pipe/venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/stier020/code/diffusion-pipe/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 3483, in broadcast_object_list
[rank0]:     broadcast(object_sizes_tensor, src=global_src, group=group)
[rank0]:   File "/home/stier020/code/diffusion-pipe/venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/stier020/code/diffusion-pipe/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2714, in broadcast
[rank0]:     work = group.broadcast([tensor], opts)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
[rank0]: ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
[rank0]: Last error:
[rank0]: cudaArch 1210 ncclMaxSharedMem 82240 exceeds device/fn maxSharedMem 79808
[rank0]:[W1020 03:42:51.271676146 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-10-20 03:42:52,714] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 61286

```

**Comment by nlienard** [comment]
on spark DGX, don't face this issue with your variables for wan 2.2 T2V (LOW): 

```
WARNING: BNB_CUDA_VERSION=130 environment variable detected; loading libbitsandbytes_cuda130.so.
This can be used to load a bitsandbytes version built with a CUDA version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=

using video_clip_mode=single_beginning
using framerate=16
Grouped metadata is not cached. Computing ungrouped metadata and then grouping.
Intermediate metadata is not cached. Enumerating all files.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:00<00:00, 58241.38it/s]
Saving intermediate metadata dataset.
Saving the dataset (1/1 shards): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 14055.98 examples/s]
Loading intermediate metadata dataset.
Caching ungrouped metadata.
Map (num_proc=8): 60 examples [00:00, 77.36 examples/s]
Grouping examples: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 11096.04it/s]
Saving the dataset (1/1 shards): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 4990.84 examples/s]
Saving the dataset (1/1 shards): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1375.81 examples/s]
Saving the dataset (1/1 shards): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1417.09 examples/s]
Loading grouped metadata with grouping key (1.26, 1)
Loading grouped metadata with grouping key (1.0, 1)
Loading grouped metadata with grouping key (0.794, 1)
caching latents: /home/xxxxx/training/work/xxxx/dataset/dataset_xxxx
caching latents: (1.26, 1)
Adding size bucket: 10 examples [00:00, 1032.72 examples/s]
caching latents: (1.26, 1152, 928, 1)
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
WARNING:datasets.arrow_dataset:num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
Building iteration order
Saving the dataset (1/1 shards): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 4715.88 examples/s]
caching latents: (1.0, 1)
Adding size bucket: 10 examples [00:00, 2800.31 examples/s]
caching latents: (1.0, 1024, 1024, 1)
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
WARNING:datasets.arrow_dataset:num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
Building iteration order
Saving the dataset (1/1 shards): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 4958.98 examples/s]
caching latents: (0.794, 1)
Adding size bucket: 40 examples [00:00, 9395.84 examples/s]
caching latents: (0.794, 928, 1152, 1)
Building iteration order
Saving the dataset (1/1 shards): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 19798.46 examples/s]
caching text embeddings: /home/xxxxx/training/work/xxxx/dataset/xxxxx
caching text embeddings: (1.26, 1)
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 3085.86 examples/s]
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
WARNING:datasets.arrow_dataset:num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
caching text embeddings: (1.0, 1)
Map: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 3475.56 examples/s]
num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
WARNING:datasets.arrow_dataset:num_proc must be <= 5. Reducing num_proc to 5 for dataset of size 5.
caching text embeddings: (0.794, 1)
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 12969.40 examples/s]
num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
WARNING:datasets.arrow_dataset:num_proc must be <= 1. Reducing num_proc to 1 for dataset of size 1.
/home/xxxxx/training/anaconda3/envs/diffusion-pipe/lib/python3.12/site-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)
Found grouped metadata cache. Directly loading it.
Loading grouped metadata with grouping key [1.26, 1]
Loading grouped metadata with grouping key [1.0, 1]
Loading grouped metadata with grouping key [0.794, 1]
caching latents: /home/xxxxx/training/work/xxxx/dataset/xxxx
caching latents: [1.26, 1]
caching latents: (1.26, 1152, 928, 1)
```

it is very slow

```
[2025-11-24 09:31:22,024] [INFO] [logging.py:107:log_dist] [Rank 0] step=8, skipped=0, lr=[8.2e-07], mom=[0.0]
steps: 8 loss: 0.1613 iter time (s): 51.601 samples/sec: 0.078
 [2025-11-24 09:32:12,908] [INFO] [logging.py:107:log_dist] [Rank 0] step=9, skipped=0, lr=[9.100000000000001e-07], mom=[0.0]
steps: 9 loss: 0.1118 iter time (s): 50.859 samples/sec: 0.079
[2025-11-24 09:33:04,055] [INFO] [logging.py:107:log_dist] [Rank 0] step=10, skipped=0, lr=[1e-06], mom=[0.0]
steps: 10 loss: 0.0785 iter time (s): 51.122 samples/sec: 0.078

```

**Comment by frauttauteffasu** [comment]
The original issue looks to be https://github.com/NVIDIA/nccl/issues/1637 which was fixed in NCCL 2.26? Do you have an older version of the nvidia-nccl-cu13 package than 2.26?

**Comment by kiskra-nvidia** [comment]
In NCCL 2.26 we fixed it for the sm_120 architecture. DGX Spark is sm_121, so it wasn't included. We expanded the fix to all sm_12x architectures in NCCL 2.27.

**Comment by shahizat** [comment]
@kiskra-nvidia thanks for the info, @johnnynunez FYI, i have two ASUS Ascent GX10s, but no QSFP cable so far, haha..

**Comment by johnnynunez** [comment]
> The original issue looks to be [NVIDIA/nccl#1637](https://github.com/NVIDIA/nccl/issues/1637) which was fixed in NCCL 2.26? Do you have an older version of the nvidia-nccl-cu13 package than 2.26?

Did you try the last one from november? 2.28?
