### ISSUE TITLE
Running failed with libcudart.so.11.0 error

### ISSUE THREAD

**Issue by jfsarazin** [tdrussell/diffusion-pipe#77]
I've got an error when I run training

```
RuntimeError: Failed to import transformers.models.bloom.modeling_bloom because of the following error (look up to see its traceback):
libcudart.so.11.0: cannot open shared object file: No such file or directory

```
I've looked into past issues, and it seems related to the CUDA version I should use. But looking at the installation doc, I could not find any information about this. I used to install cuda with commands I find there : https://pytorch.org/get-started/locally/
I tried to install version 11 or 12.4, but I've got still the issue

**Comment by tdrussell** [comment]
When I follow the README instructions and create a conda environment from scratch, I don't have any errors. But everyone's machine and environment can be different. For other ML projects, I have often gotten similar errors, so much so that I made some notes to myself. You can try installing one or both of these conda packages:

https://anaconda.org/nvidia/cuda-cudart
https://anaconda.org/nvidia/cuda-toolkit

Try just the first one to begin with. Make the version match the CUDA version you used for Pytorch. For other projects I have been able to fix some CUDA installation errors like this.

**Comment by jfsarazin** [comment]
Thanks for your answer. It still doesn't for me. I've access to another station where it works with the very same process. Difference is about gpu cards. The dual GeForce RTX 3090 can train (but in mono), but the RTX 6000 Ada Generation can't.
I tried to remove cuda packages, I try with 11 and 12 version to be sure... Still stuck :/

**Comment by jfsarazin** [comment]
If I may, there's also an ambiguity in the readme where you wrote : "Probably try to make it match the CUDA version that was installed on your system with PyTorch." Because at this step, I've just created a new conda env, with no CUDA yet. 
the process which worked for me (only for the 3090 station) was to install CUDA before with 
pip3 install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/test/cu124
